#!/bin/sh

MOVED=0

movefile() {
    if [ -f $1 ]; then
	echo Moving $1 to %OPTWARE_TARGET_PREFIX%/etc/mt-daapd/mt-daapd$2
	mv $1 %OPTWARE_TARGET_PREFIX%/etc/mt-daapd/mt-daapd$2
	MOVED=1
    fi
}

mkdir -p %OPTWARE_TARGET_PREFIX%/etc/mt-daapd

echo; echo
movefile /etc/mt-daapd.conf .conf.etc.old
movefile /etc/mt-daapd.playlist .playlist.etc.old
movefile %OPTWARE_TARGET_PREFIX%/etc/mt-daapd.conf .conf.opt.etc.old
movefile %OPTWARE_TARGET_PREFIX%/etc/mt-daapd.playlist .playlist.opt.etc.old

if [ $MOVED -eq 1 ] ; then
    # upgrade from 0.2.0 package, or a manual installation
    cp %OPTWARE_TARGET_PREFIX%/doc/mt-daapd/mt-daapd.conf %OPTWARE_TARGET_PREFIX%/etc/mt-daapd/mt-daapd.conf

    # db update from 0.2.0 to 0.2.1
    if [ -f %OPTWARE_TARGET_PREFIX%/var/mt-daapd/songs.gdb ]; then
	rm %OPTWARE_TARGET_PREFIX%/var/mt-daapd/songs.gdb
    fi
    echo
    echo "Your existing configuration has been replaced with the"
    echo "configuration file %OPTWARE_TARGET_PREFIX%/etc/mt-daapd/mt-daapd.conf"
    echo
    echo "You should review the configuration of this file, make"
    echo "any necessary changes, and complete the install by running"
    echo "%OPTWARE_TARGET_PREFIX%/etc/init.d/S60mt-daapd"
    echo
else
    echo
    echo "To complete this installation, make any necessary changes"
    echo "to the config file in  %OPTWARE_TARGET_PREFIX%/etc/mt-daapd/mt-daapd.conf, and"
    echo "start the daemon by running %OPTWARE_TARGET_PREFIX%/etc/init.d/S60mt-daapd"
    echo
fi


