#!/bin/sh

echo "With python installed, use the following command to launch admin"
echo "    %OPTWARE_TARGET_PREFIX%/sbin/cherokee-admin -b"
echo "The admin web interface is accessible at"
echo "    http://<IP-address>:9090"
