#!/bin/sh

if [ ! -d %OPTWARE_TARGET_PREFIX%/var/spool ] ;  then
    mkdir %OPTWARE_TARGET_PREFIX%/var/spool
fi

if [ ! -d %OPTWARE_TARGET_PREFIX%/var/spool/miau ] ;  then
    mkdir %OPTWARE_TARGET_PREFIX%/var/spool/miau
fi

%OPTWARE_TARGET_PREFIX%/etc/init.d/S52miau -d %OPTWARE_TARGET_PREFIX%/var/spool/miau

