#!/bin/sh

if grep -q ^jabber /etc/passwd; then
    echo There already is a jabber user on the system.
else
    echo -n "No jabber user found, creating jabber user ... "
    cat >>/etc/passwd <<EOF
jabber:x:110:500:Jabber:/opt/var/run/jabber:/opt/bin/false
EOF
    cp /etc/passwd /share/hdd/conf/
    echo ok
fi

chown -R jabber:administrators /opt/var/lib/jabber /opt/var/log/jabber /opt/var/run/jabber

/opt/etc/init.d/S80jabber restart
