*** cron/Makefile.orig	Sun Feb 13 17:52:16 2005
--- cron/Makefile	Sun Feb 13 17:52:33 2005
***************
*** 52,59 ****
  #################################### begin configurable stuff
  #<<DESTROOT is assumed to have ./etc, ./bin, and ./man subdirectories>>
! DESTROOT	=	$(DESTDIR)/usr
  DESTSBIN	=	$(DESTROOT)/sbin
  DESTBIN		=	$(DESTROOT)/bin
! DESTMAN		=	$(DESTROOT)/share/man
  #<<need bitstring.h>>
  INCLUDE		=	-I.
--- 52,59 ----
  #################################### begin configurable stuff
  #<<DESTROOT is assumed to have ./etc, ./bin, and ./man subdirectories>>
! DESTROOT	=	$(DESTDIR)
  DESTSBIN	=	$(DESTROOT)/sbin
  DESTBIN		=	$(DESTROOT)/bin
! DESTMAN		=	$(DESTROOT)/man
  #<<need bitstring.h>>
  INCLUDE		=	-I.
***************
*** 67,73 ****
  LINTFLAGS	=	-hbxa $(INCLUDE) $(DEBUGGING)
  #<<want to use a nonstandard CC?>>
! CC		=	gcc -Wall -Wno-unused -Wno-comment
  #<<manifest defines>>
! DEFS		=
  #(SGI IRIX systems need this)
  #DEFS		=	-D_BSD_SIGNALS -Dconst=
--- 67,73 ----
  LINTFLAGS	=	-hbxa $(INCLUDE) $(DEBUGGING)
  #<<want to use a nonstandard CC?>>
! CC		=	$(TARGET_CC) -Wall -Wno-unused -Wno-comment
  #<<manifest defines>>
! DEFS		= -D_PATH_VARRUN=\"/var/run\" -D_PATH_VI=\"/bin/vi\" -DCRONDIR=\"/opt/var/cron\"
  #(SGI IRIX systems need this)
  #DEFS		=	-D_BSD_SIGNALS -Dconst=
