#!/bin/sh
ln -sf	arm_920t_le-addr2line	arm-linux-addr2line
ln -sf	arm_920t_le-ar		arm-linux-ar
ln -sf	arm_920t_le-as		arm-linux-as
ln -sf	arm_920t_le-c++		arm-linux-c++
ln -sf	arm_920t_le-c++filt	arm-linux-c++filt
ln -sf	arm_920t_le-cpp		arm-linux-cpp
ln -sf	arm_920t_le-g++		arm-linux-g++
ln -sf	arm_920t_le-gcc		arm-linux-gcc
ln -sf	arm_920t_le-gcc-3.4.4	arm-linux-gcc-3.4.4
ln -sf	arm_920t_le-gvccbug	arm-linux-gvccbug
ln -sf	arm_920t_le-gcov	arm-linux-gcov
ln -sf	arm_920t_le-ld		arm-linux-ld
ln -sf	arm_920t_le-nm		arm-linux-nm
ln -sf	arm_920t_le-objcopy	arm-linux-objcopy
ln -sf	arm_920t_le-objdump	arm-linux-objdump
ln -sf	arm_920t_le-ranlib	arm-linux-ranlib
ln -sf	arm_920t_le-readelf	arm-linux-readelf
ln -sf	arm_920t_le-size	arm-linux-size
ln -sf	arm_920t_le-strings	arm-linux-strings
ln -sf	arm_920t_le-strip	arm-linux-strip
