#!/bin/sh

echo ; echo
echo "To complete the installation, you must edit %OPTWARE_TARGET_PREFIX%/etc/kissdx.conf,"
echo "and then run %OPTWARE_TARGET_PREFIX%/etc/init.d/S83kissdx to start kissdx."
echo
