#!/bin/sh

mkdir -p %OPTWARE_TARGET_PREFIX%/etc/cron.d
date "+%M * * * * root %OPTWARE_TARGET_PREFIX%/bin/ntpclient -h pool.ntp.org -s &>/dev/null" > %OPTWARE_TARGET_PREFIX%/etc/cron.d/ntpclient
chmod 600 %OPTWARE_TARGET_PREFIX%/etc/cron.d/ntpclient
