--- Makefile.orig	2007-12-09 02:23:32.000000000 +0100
+++ Makefile	2007-12-09 02:24:03.000000000 +0100
@@ -20,8 +20,8 @@
 # $Id: Makefile 236 2007-09-05 20:40:59Z Joerg Mayer $
 
 DESTDIR=
-PREFIX=/usr/local
-ETCDIR=/etc/vpnc
+PREFIX=/opt
+ETCDIR=/opt/etc/vpnc
 BINDIR=$(PREFIX)/bin
 SBINDIR=$(PREFIX)/sbin
 MANDIR=$(PREFIX)/share/man
@@ -49,13 +49,13 @@
 #OPENSSL_GPL_VIOLATION = -DOPENSSL_GPL_VIOLATION
 #OPENSSLLIBS = -lcrypto
 
-CC=gcc
+#CC=gcc
 CFLAGS ?= -O3 -g
 CFLAGS += -W -Wall -Wmissing-declarations -Wwrite-strings
-CFLAGS +=  $(shell libgcrypt-config --cflags)
+#CFLAGS +=  $(shell libgcrypt-config --cflags)
 CPPFLAGS += -DVERSION=\"$(VERSION)\" $(OPENSSL_GPL_VIOLATION)
 LDFLAGS ?= -g
-LDFLAGS += $(shell libgcrypt-config --libs) $(OPENSSLLIBS)
+#LDFLAGS += $(shell libgcrypt-config --libs) $(OPENSSLLIBS)
 
 ifeq ($(shell uname -s), SunOS)
 LDFLAGS += -lnsl -lresolv -lsocket
@@ -65,7 +65,8 @@
 CFLAGS += -fstrict-aliasing -freorder-blocks -fsched-interblock
 endif
 
-all : $(BINS) vpnc.8
+#all : $(BINS) vpnc.8
+all : $(BINS)
 
 vpnc : $(OBJS) vpnc.o
 	$(CC) -o $@ $^ $(LDFLAGS)
@@ -118,7 +119,7 @@
 	install -m600 vpnc.conf $(DESTDIR)$(ETCDIR)/default.conf
 	install -m755 vpnc-disconnect $(DESTDIR)$(SBINDIR)
 	install -m755 pcf2vpnc $(DESTDIR)$(BINDIR)
-	install -m644 vpnc.8 $(DESTDIR)$(MANDIR)/man8
+	#install -m644 vpnc.8 $(DESTDIR)$(MANDIR)/man8
 	install -m644 pcf2vpnc.1 $(DESTDIR)$(MANDIR)/man1
 	install -m644 cisco-decrypt.1 $(DESTDIR)$(MANDIR)/man1
 
