--- nail/Makefile.orig	2005-01-07 13:14:24.000000000 +0100
+++ nail/Makefile	2005-01-07 13:30:56.000000000 +0100
@@ -6,18 +6,18 @@
 # See the file INSTALL if you need help.
 #
 
-PREFIX		= /usr/local
+PREFIX		= /opt
 BINDIR		= $(PREFIX)/bin
 MANDIR		= $(PREFIX)/share/man
-SYSCONFDIR	= /etc
+SYSCONFDIR	= /opt/etc
 
 MAILRC		= $(SYSCONFDIR)/nail.rc
 MAILSPOOL	= /var/mail
-SENDMAIL	= /usr/lib/sendmail
+SENDMAIL	= /opt/bin/false
 
 DESTDIR		=
 
-UCBINSTALL	= /usr/ucb/install
+UCBINSTALL	= /usr/bin/install
 
 # Define compiler, preprocessor, and linker flags here.
 # Note that some Linux/glibc versions need -D_GNU_SOURCE in CPPFLAGS, or
