#!/bin/sh

if [ `uname -m` = armv5tel ]; then
echo "Setting up ipkg arch-file"
mkdir -p %OPTWARE_TARGET_PREFIX%/etc/ipkg
cat >> %OPTWARE_TARGET_PREFIX%/etc/ipkg/arch.conf << EOF
arch all 1
arch any 6
arch noarch 11
arch arm 16
arch ixp4xxle 21
arch slugosle 36
arch nslu2 41
EOF
fi

touch /etc/profile
if ! grep '^PATH=.*%OPTWARE_TARGET_PREFIX%/bin' /etc/profile >/dev/null 2>&1 ; then
  echo "PATH=\$PATH:%OPTWARE_TARGET_PREFIX%/bin:%OPTWARE_TARGET_PREFIX%/sbin" >> /etc/profile
fi
