#!/bin/sh

if [ `uname -m` = armv5tel ]; then
echo "Setting up ipkg arch-file"
mkdir -p /opt/etc/ipkg
cat >> /opt/etc/ipkg/arch.conf << EOF
arch all 1
arch any 6
arch noarch 11
arch arm 16
arch ixp4xxle 21
arch slugosle 36
arch nslu2 41
EOF
fi

touch /etc/profile
if ! grep '^PATH=.*/opt/bin' /etc/profile >/dev/null 2>&1 ; then
  echo "PATH=\$PATH:/opt/bin:/opt/sbin" >> /etc/profile
fi
