#!/bin/sh

echo "Generating %OPTWARE_TARGET_PREFIX%/share/glib-2.0/schemas/gschemas.compiled"
rm -f %OPTWARE_TARGET_PREFIX%/share/glib-2.0/schemas/gschemas.compiled
%OPTWARE_TARGET_PREFIX%/bin/glib-compile-schemas %OPTWARE_TARGET_PREFIX%/share/glib-2.0/schemas/
