/* This file was automagically generated by autoconf */

/* 2 moves in 64 steps of size 16384 when reallocing */
#define NOpw_class
#define NOpow
#define NOstrlcat
#define NOsetrgid
#define MAX_argc 7588
/* Your system's strstr() is 1.17 times SLOWER than my C-routine */
#define SLOWstrstr			      /* using my substitute instead */
#define UDP_protocolno 17
#define BIFF_serviceport "512"
#define IP_localhost {127,0,0,1}
#define MAILSPOOLDIR "/opt/var/spool/mail/"
#define SENDMAIL "/opt/sbin/sendmail"
#define DEFflagsendmail ""
#define CF_no_procmail_yet
#define buggy_SENDMAIL
#define defPATH "PATH=/opt/bin:$HOME/bin:/bin:/usr/bin"
#define defSPATH "PATH=/opt/bin:/bin:/usr/bin"
#define PM_VERSION "3.22"
/*locktype: 4, countlocks: 0, timeout 0, watchdog 8, /tmp/_locktest*/
/*locktype: 4, countlocks: 0, timeout 0, watchdog 8, ./_locktest*/
/*locktype: 6, countlocks: 0, timeout 0, watchdog 8, /tmp/_locktest*/
/*locktype: 6, countlocks: 0, timeout 0, watchdog 8, ./_locktest*/
/*locktype: 7, countlocks: 0, timeout 0, watchdog 8, /tmp/_locktest*/
/*locktype: 7, countlocks: 0, timeout 0, watchdog 8, ./_locktest*/
/* Hotwire LOCKINGTEST=111 */
/* Procmail will lock via: dotlocking, fcntl(), lockf(), flock() */
#define USElockf
#define USEflock
/* autoconf completed */
