#!/bin/sh

update-alternatives --install %OPTWARE_TARGET_PREFIX%/sbin/htpasswd htpasswd %OPTWARE_TARGET_PREFIX%/sbin/php-thttpd-htpasswd 50

echo ; echo
echo "To complete the installation, you must edit %OPTWARE_TARGET_PREFIX%/etc/thttpd.conf,"
echo "and then run %OPTWARE_TARGET_PREFIX%/etc/init.d/S80thttpd to start thttpd."
echo

