#!/bin/sh

update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/free free %OPTWARE_TARGET_PREFIX%/bin/procps-free 80
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/kill kill %OPTWARE_TARGET_PREFIX%/bin/procps-kill 80
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/ps ps %OPTWARE_TARGET_PREFIX%/bin/procps-ps 80
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/top top %OPTWARE_TARGET_PREFIX%/bin/procps-top 80
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/uptime uptime %OPTWARE_TARGET_PREFIX%/bin/procps-uptime 80
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/watch watch %OPTWARE_TARGET_PREFIX%/bin/procps-watch 80
