#!/bin/sh

update-alternatives --remove free %OPTWARE_TARGET_PREFIX%/bin/procps-free
update-alternatives --remove kill %OPTWARE_TARGET_PREFIX%/bin/procps-kill
update-alternatives --remove ps %OPTWARE_TARGET_PREFIX%/bin/procps-ps
update-alternatives --remove top %OPTWARE_TARGET_PREFIX%/bin/procps-top
update-alternatives --remove uptime %OPTWARE_TARGET_PREFIX%/bin/procps-uptime
update-alternatives --remove watch %OPTWARE_TARGET_PREFIX%/bin/procps-watch
