#!/bin/sh

if ! test -e %OPTWARE_TARGET_PREFIX%/etc/ld.so.conf
then rm -f %OPTWARE_TARGET_PREFIX%/etc/ld.so.conf ; echo "%OPTWARE_TARGET_PREFIX%/lib" >%OPTWARE_TARGET_PREFIX%/etc/ld.so.conf
fi

if ! test -e /etc/ld.so.conf
then rm -f /etc/ld.so.conf ; ln -s %OPTWARE_TARGET_PREFIX%/etc/ld.so.conf /etc
fi

if ! test -h /etc/ld.so.cache
then rm -f /etc/ld.so.cache ; ln -s %OPTWARE_TARGET_PREFIX%/etc/ld.so.cache /etc
fi

if ! test -e /etc/ld.so.cache
then %OPTWARE_TARGET_PREFIX%/sbin/ldconfig
fi
