#!/bin/sh

update-alternatives --remove scp %OPTWARE_TARGET_PREFIX%/sbin/dropbearmulti
update-alternatives --remove ssh %OPTWARE_TARGET_PREFIX%/sbin/dropbearmulti

killall dropbear

rm -f %OPTWARE_TARGET_PREFIX%/etc/dropbear/dropbear_rsa_host_key
rm -f %OPTWARE_TARGET_PREFIX%/etc/dropbear/dropbear_dss_host_key
rm -f %OPTWARE_TARGET_PREFIX%/etc/dropbear/dropbear_ecdsa_host_key
