#!/bin/sh

/opt/bin/update-alternatives --remove scp /opt/sbin/dropbearmulti
/opt/bin/update-alternatives --remove ssh /opt/sbin/dropbearmulti

killall dropbear

rm -f /opt/etc/dropbear/dropbear_rsa_host_key
rm -f /opt/etc/dropbear/dropbear_dss_host_key
rm -f /opt/etc/dropbear/dropbear_ecdsa_host_key
