#!/bin/sh
echo "Testing Electric Fence."
if %OPTWARE_TARGET_PREFIX%/bin/eftest && %OPTWARE_TARGET_PREFIX%/bin/tstheap 3072 ; then
  echo ""
  echo "Electric Fence confidence test PASSED." 
  echo ""
else
  echo "Electric Fence confidence test FAILED!"
fi
