#!/bin/sh

mkdir -p %OPTWARE_TARGET_PREFIX%/lib/girepository-1.0

cd %OPTWARE_TARGET_PREFIX%/share/gir-1.0

for src in `ls *.gir|sed 's/\.gir$//g'`; do
	echo "Generating %OPTWARE_TARGET_PREFIX%/lib/girepository-1.0/${src}.typelib"
	PATH="%OPTWARE_TARGET_PREFIX%/bin:$PATH" g-ir-compiler --includedir=. ${src}.gir -o %OPTWARE_TARGET_PREFIX%/lib/girepository-1.0/${src}.typelib
done
