--- iozone3_283/src/current/makefile.orig	2007-02-19 18:12:18.000000000 +0100
+++ iozone3_283/src/current/makefile	2007-07-05 14:13:15.000000000 +0200
@@ -9,12 +9,12 @@
 #		convex, FreeBSD, OpenBSD, OSFV3, OSFV4, OSFV5, SCO
 #		SCO_Unixware_gcc,NetBSD,TRU64, Mac OS X
 
-CC	= cc
-C89	= c89
+#CC	= cc
+#C89	= c89
 GCC	= gcc
 CCS	= /usr/ccs/bin/cc
 NACC	= /opt/ansic/bin/cc
-CFLAGS	=
+#CFLAGS	=
 S10GCCFLAGS    = -m64 -mcpu=v9
 
 all:  
