#!/bin/sh

[ -e %OPTWARE_TARGET_PREFIX% ] || mkdir %OPTWARE_TARGET_PREFIX%
# [ -e /home/optware ] || mkdir -p /home/optware
# mount -o bind /home/optware %OPTWARE_TARGET_PREFIX%
[ -d %OPTWARE_TARGET_PREFIX%/etc/ipkg ] || mkdir -p %OPTWARE_TARGET_PREFIX%/etc/ipkg
[ -d %OPTWARE_TARGET_PREFIX%/var ] || mkdir -p %OPTWARE_TARGET_PREFIX%/var/lib
[ -d %OPTWARE_TARGET_PREFIX%/tmp ] || mkdir -p %OPTWARE_TARGET_PREFIX%/tmp
[ -d %OPTWARE_TARGET_PREFIX%/lib/ipkg/info ] || mkdir -p %OPTWARE_TARGET_PREFIX%/lib/ipkg/info
[ -d /usr/lib/ipkg/info ] || mkdir -p /usr/lib/ipkg/info
