#!/bin/sh

update-alternatives --install /opt/bin/chpasswd chpasswd /opt/bin/adduser 30
update-alternatives --install /opt/bin/cryptpw cryptpw /opt/bin/adduser 30
update-alternatives --install /opt/bin/getty getty /opt/bin/adduser 30
update-alternatives --install /opt/bin/login login /opt/bin/adduser 30
update-alternatives --install /opt/bin/mkpasswd mkpasswd /opt/bin/adduser 30
update-alternatives --install /opt/bin/passwd passwd /opt/bin/adduser 30
update-alternatives --install /opt/bin/su su /opt/bin/adduser 30
update-alternatives --install /opt/bin/sulogin sulogin /opt/bin/adduser 30
update-alternatives --install /opt/bin/vlock vlock /opt/bin/adduser 30
