#!/bin/sh

### remove deprecated links
update-alternatives --remove chpasswd %OPTWARE_TARGET_PREFIX%/bin/adduser 30
update-alternatives --remove cryptpw %OPTWARE_TARGET_PREFIX%/bin/adduser 30
update-alternatives --remove getty %OPTWARE_TARGET_PREFIX%/bin/adduser 30
update-alternatives --remove login %OPTWARE_TARGET_PREFIX%/bin/adduser 30
update-alternatives --remove mkpasswd %OPTWARE_TARGET_PREFIX%/bin/adduser 30
update-alternatives --remove passwd %OPTWARE_TARGET_PREFIX%/bin/adduser 30
update-alternatives --remove su %OPTWARE_TARGET_PREFIX%/bin/adduser 30
update-alternatives --remove sulogin %OPTWARE_TARGET_PREFIX%/bin/adduser 30
update-alternatives --remove vlock %OPTWARE_TARGET_PREFIX%/bin/adduser 30

### add right ones
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/addgroup addgroup %OPTWARE_TARGET_PREFIX%/bin/adduser-dir/busybox 30
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/adduser adduser %OPTWARE_TARGET_PREFIX%/bin/adduser-dir/busybox 30
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/delgroup delgroup %OPTWARE_TARGET_PREFIX%/bin/adduser-dir/busybox 30
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/deluser deluser %OPTWARE_TARGET_PREFIX%/bin/adduser-dir/busybox 30
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/chpasswd chpasswd %OPTWARE_TARGET_PREFIX%/bin/adduser-dir/busybox 30
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/cryptpw cryptpw %OPTWARE_TARGET_PREFIX%/bin/adduser-dir/busybox 30
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/getty getty %OPTWARE_TARGET_PREFIX%/bin/adduser-dir/busybox 30
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/login login %OPTWARE_TARGET_PREFIX%/bin/adduser-dir/busybox 30
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/mkpasswd mkpasswd %OPTWARE_TARGET_PREFIX%/bin/adduser-dir/busybox 30
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/passwd passwd %OPTWARE_TARGET_PREFIX%/bin/adduser-dir/busybox 30
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/su su %OPTWARE_TARGET_PREFIX%/bin/adduser-dir/busybox 30
update-alternatives --install %OPTWARE_TARGET_PREFIX%/sbin/sulogin sulogin %OPTWARE_TARGET_PREFIX%/bin/adduser-dir/busybox 30
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/vlock vlock %OPTWARE_TARGET_PREFIX%/bin/adduser-dir/busybox 30
