#!/bin/sh

update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/chpasswd chpasswd %OPTWARE_TARGET_PREFIX%/bin/adduser 30
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/cryptpw cryptpw %OPTWARE_TARGET_PREFIX%/bin/adduser 30
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/getty getty %OPTWARE_TARGET_PREFIX%/bin/adduser 30
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/login login %OPTWARE_TARGET_PREFIX%/bin/adduser 30
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/mkpasswd mkpasswd %OPTWARE_TARGET_PREFIX%/bin/adduser 30
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/passwd passwd %OPTWARE_TARGET_PREFIX%/bin/adduser 30
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/su su %OPTWARE_TARGET_PREFIX%/bin/adduser 30
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/sulogin sulogin %OPTWARE_TARGET_PREFIX%/bin/adduser 30
update-alternatives --install %OPTWARE_TARGET_PREFIX%/bin/vlock vlock %OPTWARE_TARGET_PREFIX%/bin/adduser 30
