#!/bin/sh

# Create start up and shut down symbolic links
ln -sf %OPTWARE_TARGET_PREFIX%/var/MailRoot/xmail %OPTWARE_TARGET_PREFIX%/etc/init.d/K27xmail
ln -sf %OPTWARE_TARGET_PREFIX%/var/MailRoot/xmail %OPTWARE_TARGET_PREFIX%/etc/init.d/S43xmail

