#!/bin/sh

# Shut down xmail
%OPTWARE_TARGET_PREFIX%/etc/init.d/K27xmail stop

# Discard the symbolic links
rm -rf %OPTWARE_TARGET_PREFIX%/etc/init.d/K27xmail
rm -rf %OPTWARE_TARGET_PREFIX%/etc/init.d/S43xmail

