#! /bin/ash
#
echo "Running post-install"
#
mkdir -p %OPTWARE_TARGET_PREFIX%/var/named
mkdir -p %OPTWARE_TARGET_PREFIX%/var/run
#
# This hack seems to be necessary; I suspect that
# the IPK installer confuses the named executable & 
# the opt/etc/directory of the same name.
# The image IS in the data tarball of the kit.
#
#if [ ! -e %OPTWARE_TARGET_PREFIX%/sbin/named ]; then 
#    echo "Missing named, using redundant copy"
#    mv %OPTWARE_TARGET_PREFIX%/sbin/named.exe %OPTWARE_TARGET_PREFIX%/sbin/named 
#else
#    rm -f %OPTWARE_TARGET_PREFIX%/sbin/named.exe
#fi
#if [ -n "`%OPTWARE_TARGET_PREFIX%/bin/pidof named`" ]; then
#    %OPTWARE_TARGET_PREFIX%/bin/killall named 2>/dev/null
#fi

# Register for shutdown/halt

ln -sf %OPTWARE_TARGET_PREFIX%/etc/init.d/S09named %OPTWARE_TARGET_PREFIX%/etc/init.d/K91named

echo "You must now create your named.conf file"
echo "When it is installed in %OPTWARE_TARGET_PREFIX%/etc/named/named.conf, execute"
echo "              %OPTWARE_TARGET_PREFIX%/etc/init.d/S09named start"
echo "to start service"
echo "You will probably also want to create rndc.conf by running"
echo "rndc-confgen.  Of course, you may want to set your name server"
echo "in the GUI to 127.0.0.1 or your local ip-address"
