#!/bin/sh
#
echo "Running bind pre-remove"
#
if [ -n "`%OPTWARE_TARGET_PREFIX%/bin/pidof named`" ]; then
    %OPTWARE_TARGET_PREFIX%/bin/killall named 2>/dev/null
fi

rm -f %OPTWARE_TARGET_PREFIX%/etc/init.d/K91named 
