#!/bin/sh
#
# Start the named (DNS) server daemon
#  

start() {
    echo -n "Starting DNS Services: "
    if [ -n "`%OPTWARE_TARGET_PREFIX%/bin/busybox pidof named`" ]; then
	echo "already running..."
	false; 
	return
    fi
    cd %OPTWARE_TARGET_PREFIX%/etc/named
    %OPTWARE_TARGET_PREFIX%/sbin/named -c %OPTWARE_TARGET_PREFIX%/etc/named/named.conf 
    echo "started"
    return
}
stop() {
    echo "Shutting down DNS Services: "
    %OPTWARE_TARGET_PREFIX%/sbin/rndc -s 127.0.0.1 stop
    sleep 5
    if [ -n "`%OPTWARE_TARGET_PREFIX%/bin/busybox pidof named`" ]; then
        echo -n "Failed, killing process"
	%OPTWARE_TARGET_PREFIX%/bin/killall named 2>/dev/null
    fi
    return
}
bindstatus() {
    %OPTWARE_TARGET_PREFIX%/sbin/rndc -s 127.0.0.1 status
    return
}
restart() {
    stop
    start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	bindstatus
	;;
  restart|reload)
	restart
	;;
  condrestart)
	[ -n "`%OPTWARE_TARGET_PREFIX%/bin/busybox pidof named`" ] && restart
	;;
  *)
	echo "Usage: $0 {start|stop|status|restart|condrestart}"
	exit 1
esac
exit $?
