#!/bin/sh

mkdir -p /opt/etc/gtk-3.0

### configure gdk-pixbuf
rm -f /opt/etc/gtk-3.0/gdk-pixbuf.loaders
/opt/bin/gdk-pixbuf-query-loaders > /opt/etc/gtk-3.0/gdk-pixbuf.loaders

### configure input modules
rm -f /opt/etc/gtk-3.0/gtk.immodules
/opt/bin/gtk-query-immodules-3.0 > /opt/etc/gtk-3.0/gtk.immodules
