#!/bin/sh

if [ `uname -m` = i686 ]; then
echo "Setting up ipkg arch-file"
mkdir -p %OPTWARE_TARGET_PREFIX%/etc/ipkg
cat >> %OPTWARE_TARGET_PREFIX%/etc/ipkg/arch.conf << EOF
arch all 1
arch any 6
arch noarch 11
arch i686 16
arch qemux86 21
EOF
fi

mkdir -p /etc/profile.d/

cat >> /etc/profile.d/optware << EOF
PATH=$PATH:%OPTWARE_TARGET_PREFIX%/bin
if [ "`id -u`" -eq 0 ]; then
  PATH=$PATH:%OPTWARE_TARGET_PREFIX%/sbin
fi
EOF

