#!/bin/sh

#in case this install is an update with gtk or gtk2 already installed
if test -x %OPTWARE_TARGET_PREFIX%/bin/gtk-update-icon-cache; then
	echo "Update icon cache: gnome-icon-theme"
	%OPTWARE_TARGET_PREFIX%/bin/gtk-update-icon-cache %OPTWARE_TARGET_PREFIX%/share/icons/gnome
elif test -x %OPTWARE_TARGET_PREFIX%/bin/gtk-2.0/gtk-update-icon-cache; then
	echo "Update icon cache: gnome-icon-theme"
	%OPTWARE_TARGET_PREFIX%/bin/gtk-2.0/gtk-update-icon-cache %OPTWARE_TARGET_PREFIX%/share/icons/gnome
fi
