--- makefile.orig	2007-02-02 07:12:20.000000000 -0800
+++ makefile	2007-04-09 18:50:16.000000000 -0700
@@ -10,15 +10,15 @@
 else
 OS_CCDEFS = -D_GNU_SOURCE
 endif
-CC = gcc -std=c99 -O2 -U__STRICT_ANSI__ -g -lm -lrt $(OS_CCDEFS) -I .
+CC = $(TARGET_CC) -std=c99 -O2 -U__STRICT_ANSI__ -g -lm -lrt $(OS_CCDEFS) -I .
 ifeq ($(USE_NETWORK),)
 else
-NETWORK_OPT = -DUSE_NETWORK -isystem /usr/local/include /usr/local/lib/libpcap.a
+NETWORK_OPT = -DUSE_NETWORK -isystem $(CPPFLAGS) -lpcap
 endif
 else
 #Win32 Environments
 LDFLAGS = -lm -lwsock32 -lwinmm
-CC = gcc -std=c99 -U__STRICT_ANSI__ -O0 -I.
+CC = $(TARGET_CC) -std=c99 -U__STRICT_ANSI__ -O0 -I.
 EXE = .exe
 ifeq ($(USE_NETWORK),)
 else
