#!/bin/sh
#
# Startup script for proftpd as standalone server
#

if [ -n "`%OPTWARE_TARGET_PREFIX%/bin/pidof proftpd`" ]; then
    %OPTWARE_TARGET_PREFIX%/bin/killall proftpd 2>/dev/null
fi

%OPTWARE_TARGET_PREFIX%/sbin/proftpd --config %OPTWARE_TARGET_PREFIX%/etc/proftpd.conf


