#!/bin/sh

mkdir -p %OPTWARE_TARGET_PREFIX%/var/lib/rrd
chmod ugo+rx %OPTWARE_TARGET_PREFIX%/var/lib/rrd

mkdir -p %OPTWARE_TARGET_PREFIX%/var/lib/drraw
chmod ugo+rx %OPTWARE_TARGET_PREFIX%/var/lib/drraw

mkdir -p %OPTWARE_TARGET_PREFIX%/var/lib/drraw/saved
chmod ugo+rwx %OPTWARE_TARGET_PREFIX%/var/lib/drraw/saved

mkdir -p %OPTWARE_TARGET_PREFIX%/var/lib/drraw/tmp
chmod ugo+rwx %OPTWARE_TARGET_PREFIX%/var/lib/drraw/tmp

chmod ugo+rx %OPTWARE_TARGET_PREFIX%/share/www/cgi-bin/drraw.cgi
