#!/bin/sh

echo
echo "Please edit %OPTWARE_TARGET_PREFIX%/etc/heyu/x10.conf and %OPTWARE_TARGET_PREFIX%/etc/heyu/x10.sched"
echo "(typically, set TTY to something like /dev/usb/tts/0)"
echo "and start %OPTWARE_TARGET_PREFIX%/etc/init.d/S99heyu"
echo
