#!/bin/sh

cd /opt/share/gir-1.0

echo "Generating /opt/lib/girepository-1.0/Atk-1.0.typelib"
PATH="/opt/bin:$PATH" g-ir-compiler --includedir=. Atk-1.0.gir -o /opt/lib/girepository-1.0/Atk-1.0.typelib
