#!/bin/sh

cd %OPTWARE_TARGET_PREFIX%/share/gir-1.0

echo "Generating %OPTWARE_TARGET_PREFIX%/lib/girepository-1.0/Atk-1.0.typelib"
PATH="%OPTWARE_TARGET_PREFIX%/bin:$PATH" g-ir-compiler --includedir=. Atk-1.0.gir -o %OPTWARE_TARGET_PREFIX%/lib/girepository-1.0/Atk-1.0.typelib
