#!/bin/sh
#
# Startup script for byRequest daemon
#

if [ -n "`%OPTWARE_TARGET_PREFIX%/bin/pidof byRequest`" ]; then
    %OPTWARE_TARGET_PREFIX%/bin/killall byRequest 2>/dev/null
fi

%OPTWARE_TARGET_PREFIX%/bin/byRequest %OPTWARE_TARGET_PREFIX%/etc/byRequest.conf


