#!/bin/sh

echo ; echo
echo "To complete the installation, you must edit %OPTWARE_TARGET_PREFIX%/etc/siproxd.conf-example and rename it to %OPTWARE_TARGET_PREFIX%/etc/siproxd.conf,"
echo "and then run %OPTWARE_TARGET_PREFIX%/etc/init.d/S90siproxd to start siproxd."
echo

