--- Makefile.org	2003-03-08 12:50:57.000000000 +0100
+++ Makefile	2006-12-16 14:27:46.000000000 +0100
@@ -13,10 +13,6 @@
 #
 #
 
-CPPFLAGS=-DREENTRANT -D_LARGEFILE64_SOURCE  -Wall -Wshadow -O3
-
-LDFLAGS= -s -static
-
 INSTALL=/usr/bin/install 
 DESTDIR=/usr/local
 
