--- cogito-0.10/Makefile	2005-05-08 16:55:36.000000000 -0700
+++ cogito/Makefile	2005-05-09 19:05:10.109398000 -0700
@@ -21,6 +21,7 @@
 
 # DEFINES += -DNSEC
 
+CPPFLAGS=
 CFLAGS?=-g -O2
 CFLAGS+=-Wall $(DEFINES)
 
@@ -84,7 +85,7 @@
 endif
 endif
 
-CFLAGS += '-DSHA1_HEADER=$(SHA1_HEADER)'
+CFLAGS += $(CPPFLAGS) '-DSHA1_HEADER=$(SHA1_HEADER)'
 
 
 all: $(PROG) $(GEN_SCRIPT)
@@ -129,7 +130,7 @@
 	sed -e 's/@@VERSION@@/$(shell cat $(VERSION) | cut -d"-" -f2)/g' < $< > $@
 
 
-sedlibdir=$(shell echo $(libdir) | sed 's/\//\\\//g')
+sedlibdir=$(shell echo "/opt/lib/cogito" | sed 's/\//\\\//g')
 
 install: $(PROG) $(SCRIPTS) $(SCRIPT) $(LIB_SCRIPT) $(GEN_SCRIPT)
 	$(INSTALL) -m755 -d $(DESTDIR)$(bindir)
@@ -147,6 +148,10 @@
 		cat $$file.new > $$file; rm $$file.new; \
 	done
 
+install-strip: install
+	for p in $(PROG); do $(STRIP) $(DESTDIR)$(bindir)/$$p; done
+
+
 uninstall:
 	cd $(DESTDIR)$(bindir) && rm $(PROG) $(SCRIPTS) $(SCRIPT) $(GEN_SCRIPT)
 	cd $(DESTDIR)$(libdir) && rm $(LIB_SCRIPT)
