--- cogito/Makefile-orig	2005-05-09 16:47:47.000000000 -0700
+++ cogito/Makefile	2005-05-09 17:17:57.000000000 -0700
@@ -21,6 +21,7 @@
 
 # DEFINES += -DNSEC
 
+CPPFLAGS=
 CFLAGS?=-g -O2
 CFLAGS+=-Wall $(DEFINES)
 
@@ -84,7 +85,7 @@
 endif
 endif
 
-CFLAGS += '-DSHA1_HEADER=$(SHA1_HEADER)'
+CFLAGS += $(CPPFLAGS) '-DSHA1_HEADER=$(SHA1_HEADER)'
 
 
 all: $(PROG) $(GEN_SCRIPT)
@@ -147,6 +148,10 @@
 		cat $$file.new > $$file; rm $$file.new; \
 	done
 
+install-strip: install
+	for p in $(PROG); do $(STRIP) $(DESTDIR)$(bindir)/$$p; done
+
+
 uninstall:
 	cd $(DESTDIR)$(bindir) && rm $(PROG) $(SCRIPTS) $(SCRIPT) $(GEN_SCRIPT)
 	cd $(DESTDIR)$(libdir) && rm $(LIB_SCRIPT)
