#!/bin/sh

# Back up squid.conf file

if [ -f %OPTWARE_TARGET_PREFIX%/etc/squid/squid.conf ] ; then
   echo "squid.conf -> squid.conf.old"
   cp %OPTWARE_TARGET_PREFIX%/etc/squid/squid.conf %OPTWARE_TARGET_PREFIX%/etc/squid/squid.conf.ipkg-old
fi

