#!/bin/sh

%OPTWARE_TARGET_PREFIX%/bin/killall slapd

/bin/rm -rf %OPTWARE_TARGET_PREFIX%/etc/openldap
/bin/rm -rf %OPTWARE_TARGET_PREFIX%/var/openldap-slurp
/bin/rm -rf %OPTWARE_TARGET_PREFIX%/var/openldap-data

