#!/bin/sh

if [ -f /usr/lib/sasl2 ] ; then
    ln -s %OPTWARE_TARGET_PREFIX%/lib/sasl2 /usr/lib/sasl2 > /dev/null 2>&1
fi

echo
echo Please read the man page of saslauthd and
echo "check settings in %OPTWARE_TARGET_PREFIX%/etc/init.d/S52saslauthd "
echo
echo "If you dislike the link /usr/lib/sasl2 -> %OPTWARE_TARGET_PREFIX%/lib/sasl2"
echo then you may want to set SASL_PATH instead
echo

%OPTWARE_TARGET_PREFIX%/etc/init.d/S52saslauthd start
