#!/bin/sh

%OPTWARE_TARGET_PREFIX%/bin/killall saslauthd > /dev/null 2>&1

/bin/rm -rf %OPTWARE_TARGET_PREFIX%/etc/sasl2
/bin/rm -rf %OPTWARE_TARGET_PREFIX%/lib/sasl2
/bin/rm -rf /var/state/saslauthd
