#! /bin/sh

if test -z "${REAL_OPT_DIR}"; then
# next line to be replaced according to OPTWARE_TARGET
REAL_OPT_DIR=
fi

case "$1" in
    start)
        echo "Starting Optware."
        if test -n "${REAL_OPT_DIR}"; then
            if ! grep ' %OPTWARE_TARGET_PREFIX% ' /proc/mounts >/dev/null 2>&1 ; then
                mkdir -p %OPTWARE_TARGET_PREFIX%
                mount -o bind ${REAL_OPT_DIR} %OPTWARE_TARGET_PREFIX%
            fi	
        fi
	[ -x %OPTWARE_TARGET_PREFIX%/etc/rc.optware ] && %OPTWARE_TARGET_PREFIX%/etc/rc.optware
    ;;
    reconfig)
	true
    ;;
    stop)
        echo "Shutting down Optware."
	true
    ;;
    *)
        echo "Usage: $0 {start|stop|reconfig}"
        exit 1
esac

exit 0
