--- ftpd-topfield/Makefile.orig	2005-04-04 07:05:37.000000000 +0930
+++ ftpd-topfield/Makefile	2005-04-04 07:05:52.000000000 +0930
@@ -2,7 +2,7 @@
 CFLAGS += -I . -I ../libtopfield
 
 CFLAGS += -Wall -Werror -D_FILE_OFFSET_BITS=64
-CFLAGS += -DHAVE_ERR -DKEEP_OPEN=1 -D_GNU_SOURCE
+CFLAGS += -DKEEP_OPEN=1 -D_GNU_SOURCE
 CFLAGS += -DPATH_FTPDPID=\"ftpd.pid\"
 CFLAGS += -DHAVE_CONFIG_H=1
 CFLAGS += -DPATH_FTPWELCOME=\"ftpwelcome\"
