#!/bin/ash

ln -sf %OPTWARE_TARGET_PREFIX%/gcc-3.3.5-glibc-2.2.5 %OPTWARE_TARGET_PREFIX%/gcc

ln -sf %OPTWARE_TARGET_PREFIX%/gcc/bin/armv5b-softfloat-linux-addr2line %OPTWARE_TARGET_PREFIX%/bin/addr2line
ln -sf %OPTWARE_TARGET_PREFIX%/gcc/bin/armv5b-softfloat-linux-ar %OPTWARE_TARGET_PREFIX%/bin/ar
ln -sf %OPTWARE_TARGET_PREFIX%/gcc/bin/armv5b-softfloat-linux-as %OPTWARE_TARGET_PREFIX%/bin/as
ln -sf %OPTWARE_TARGET_PREFIX%/gcc/bin/armv5b-softfloat-linux-c++ %OPTWARE_TARGET_PREFIX%/bin/c++
ln -sf %OPTWARE_TARGET_PREFIX%/gcc/bin/armv5b-softfloat-linux-c++filt %OPTWARE_TARGET_PREFIX%/bin/c++filt
ln -sf %OPTWARE_TARGET_PREFIX%/gcc/bin/armv5b-softfloat-linux-cpp %OPTWARE_TARGET_PREFIX%/bin/cpp
ln -sf %OPTWARE_TARGET_PREFIX%/gcc/bin/armv5b-softfloat-linux-g++ %OPTWARE_TARGET_PREFIX%/bin/g++
ln -sf %OPTWARE_TARGET_PREFIX%/gcc/bin/armv5b-softfloat-linux-gcc %OPTWARE_TARGET_PREFIX%/bin/gcc
ln -sf %OPTWARE_TARGET_PREFIX%/gcc/bin/armv5b-softfloat-linux-gcc-3.3.5 %OPTWARE_TARGET_PREFIX%/bin/gcc-3.3.5
ln -sf %OPTWARE_TARGET_PREFIX%/gcc/bin/armv5b-softfloat-linux-gccbug %OPTWARE_TARGET_PREFIX%/bin/gccbug
ln -sf %OPTWARE_TARGET_PREFIX%/gcc/bin/armv5b-softfloat-linux-gcov %OPTWARE_TARGET_PREFIX%/bin/gcov
ln -sf %OPTWARE_TARGET_PREFIX%/gcc/bin/armv5b-softfloat-linux-gprof %OPTWARE_TARGET_PREFIX%/bin/gprof
ln -sf %OPTWARE_TARGET_PREFIX%/gcc/bin/armv5b-softfloat-linux-ld %OPTWARE_TARGET_PREFIX%/bin/ld
ln -sf %OPTWARE_TARGET_PREFIX%/gcc/bin/armv5b-softfloat-linux-nm %OPTWARE_TARGET_PREFIX%/bin/nm
ln -sf %OPTWARE_TARGET_PREFIX%/gcc/bin/armv5b-softfloat-linux-objcopy %OPTWARE_TARGET_PREFIX%/bin/objcopy
ln -sf %OPTWARE_TARGET_PREFIX%/gcc/bin/armv5b-softfloat-linux-objdump %OPTWARE_TARGET_PREFIX%/bin/objdump
ln -sf %OPTWARE_TARGET_PREFIX%/gcc/bin/armv5b-softfloat-linux-ranlib %OPTWARE_TARGET_PREFIX%/bin/ranlib
ln -sf %OPTWARE_TARGET_PREFIX%/gcc/bin/armv5b-softfloat-linux-readelf %OPTWARE_TARGET_PREFIX%/bin/readelf
ln -sf %OPTWARE_TARGET_PREFIX%/gcc/bin/armv5b-softfloat-linux-size %OPTWARE_TARGET_PREFIX%/bin/size
ln -sf %OPTWARE_TARGET_PREFIX%/gcc/bin/armv5b-softfloat-linux-strings %OPTWARE_TARGET_PREFIX%/bin/strings
ln -sf %OPTWARE_TARGET_PREFIX%/gcc/bin/armv5b-softfloat-linux-strip %OPTWARE_TARGET_PREFIX%/bin/strip

