--- asterisk-1.0.99/Makefile~	2005-04-02 12:32:12.000000000 -0800
+++ asterisk-1.0.99/Makefile	2005-04-02 12:29:26.000000000 -0800
@@ -11,7 +11,8 @@
 # the GNU General Public License
 #
 
-.EXPORT_ALL_VARIABLES:
+#.EXPORT_ALL_VARIABLES:
+export
 
 # Create OPTIONS variable
 OPTIONS=
@@ -61,7 +62,7 @@
 OPTIONS+=-fsigned-char -mcpu=ep9312
 else
 ifeq ($(SUB_PROC),xscale)
-OPTIONS+=-fsigned-char -msoft-float -mcpu=xscale
+OPTIONS+=-fsigned-char -mcpu=xscale -mbig-endian
 else
 OPTIONS+=-fsigned-char -msoft-float 
 endif
@@ -101,10 +102,10 @@
 OVERWRITE=y
 
 #Tell gcc to optimize the asterisk's code
-OPTIMIZE+=-O6
+OPTIMIZE+=-Os
 
 #Include debug symbols in the executables (-g) and profiling info (-pg)
-DEBUG=-g #-pg
+DEBUG=#-g #-pg
 
 # If you are running a radio application, define RADIO_RELAX so that the DTMF
 # will be received more reliably
@@ -169,6 +170,7 @@
 
 INCLUDE=-Iinclude -I../include
 CFLAGS=-pipe  -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations $(DEBUG) $(INCLUDE) -D_REENTRANT -D_GNU_SOURCE #-DMAKE_VALGRIND_HAPPY
+CFLAGS+=$(CPPFLAGS)
 CFLAGS+=$(OPTIMIZE)
 
 ifneq ($(PROC),ultrasparc)
@@ -271,8 +273,8 @@
 ASTLINK=-Wl,-dynamic
 SOLINK=-dynamic -bundle -undefined suppress -force_flat_namespace
 else
-ASTLINK=-Wl,-E 
-SOLINK=-shared -Xlinker -x
+ASTLINK= $(LDFLAGS) -Wl,-E 
+SOLINK= $(LDFLAGS) -shared -Xlinker -x
 endif
 ifeq (${OSARCH},SunOS)
 OBJS+=strcompat.o
