#!/bin/sh

/bin/chown 0:0 /opt/bin/su
/bin/chmod 4755 /opt/bin/su

update-alternatives --install /opt/bin/kill kill /opt/bin/coreutils-kill 50
update-alternatives --install /opt/bin/uptime uptime /opt/bin/coreutils-uptime 50
