#!/bin/sh

addgroup clamav

adduser -s /dev/null -H -h /opt/share/clamav -D -G clamav clamav

#my=`grep clamav /etc/passwd | awk -F: '{ print $4 }'`
#sed -i "s/^$my/clamav/g" /etc/group

chown clamav:clamav /opt/share/clamav
chown clamav:clamav /opt/share/clamav/*

mkdir -p /opt/var/log/clamav
chown clamav:clamav /opt/var/log/clamav

touch /opt/var/log/clamav/freshclam.log
chown clamav:clamav /opt/var/log/clamav/freshclam.log 

