#!/bin/sh

echo "To complete the installation you must" 
echo "add a new user clamav and also a new group clamav"
echo "Make sure that the directory /opt/share/clamav is owned by clamav"
echo "$ chown clamav /opt/share/clamav"
echo "and the owned group is also clamav"
echo "$ chgrp clamav /opt/share/clamav"

