#!/bin/ash

ln -sf /opt/gcc-3.3.4-glibc-2.2.5 /opt/gcc

ln -sf /opt/gcc/bin/armv5b-softfloat-linux-addr2line /opt/bin/addr2line
ln -sf /opt/gcc/bin/armv5b-softfloat-linux-ar /opt/bin/ar
ln -sf /opt/gcc/bin/armv5b-softfloat-linux-as /opt/bin/as
ln -sf /opt/gcc/bin/armv5b-softfloat-linux-c++ /opt/bin/c++
ln -sf /opt/gcc/bin/armv5b-softfloat-linux-c++filt /opt/bin/c++filt
ln -sf /opt/gcc/bin/armv5b-softfloat-linux-cpp /opt/bin/cpp
ln -sf /opt/gcc/bin/armv5b-softfloat-linux-g++ /opt/bin/g++
ln -sf /opt/gcc/bin/armv5b-softfloat-linux-gcc /opt/bin/gcc
ln -sf /opt/gcc/bin/armv5b-softfloat-linux-gcc-3.3.4 /opt/bin/gcc-3.3.4
ln -sf /opt/gcc/bin/armv5b-softfloat-linux-gccbug /opt/bin/gccbug
ln -sf /opt/gcc/bin/armv5b-softfloat-linux-gcov /opt/bin/gcov
ln -sf /opt/gcc/bin/armv5b-softfloat-linux-gprof /opt/bin/gprof
ln -sf /opt/gcc/bin/armv5b-softfloat-linux-ld /opt/bin/ld
ln -sf /opt/gcc/bin/armv5b-softfloat-linux-nm /opt/bin/nm
ln -sf /opt/gcc/bin/armv5b-softfloat-linux-objcopy /opt/bin/objcopy
ln -sf /opt/gcc/bin/armv5b-softfloat-linux-objdump /opt/bin/objdump
ln -sf /opt/gcc/bin/armv5b-softfloat-linux-ranlib /opt/bin/ranlib
ln -sf /opt/gcc/bin/armv5b-softfloat-linux-readelf /opt/bin/readelf
ln -sf /opt/gcc/bin/armv5b-softfloat-linux-size /opt/bin/size
ln -sf /opt/gcc/bin/armv5b-softfloat-linux-strings /opt/bin/strings
ln -sf /opt/gcc/bin/armv5b-softfloat-linux-strip /opt/bin/strip

