#!/bin/sh
echo "To activate metalog:"
echo " - Uncomment the first line of /etc/inittab to disable syslog"
echo " - Copy /opt/doc/metalog/rc to /unslung (if /unslung/rc exists, merge them)"
echo "To start metalog afterwards, reboot."

return 0
