TARGET_ARCH=arm
TARGET_OS=darwin
LIBC_STYLE=glibc
GNU_TARGET_NAME = arm-apple-darwin

CROSS_CONFIGURATION_GCC_VERSION=4.2.1
CROSS_CONFIGURATION_GLIBC_VERSION=2.3.5
CROSS_CONFIGURATION_GCC=gcc-$(CROSS_CONFIGURATION_GCC_VERSION)
CROSS_CONFIGURATION_GLIBC=glibc-$(CROSS_CONFIGURATION_GLIBC_VERSION)
CROSS_CONFIGURATION = $(CROSS_CONFIGURATION_GCC)-$(CROSS_CONFIGURATION_GLIBC)

STAGING_LDFLAGS=$(TARGET_LDFLAGS) -L$(STAGING_LIB_DIR)
STRIP_COMMAND=$(TARGET_STRIP)

ifeq ($(HOST_MACHINE),arm)
HOSTCC = $(TARGET_CC)
GNU_HOST_NAME = $(GNU_TARGET_NAME)
#TARGET_CROSS = /usr/bin/$(GNU_TARGET_NAME)-
#TARGET_LIBDIR = /usr/lib
#TARGET_INCDIR = /usr/include
#TARGET_LDFLAGS =
#TARGET_CUSTOM_FLAGS=
#TARGET_CFLAGS=$(TARGET_OPTIMIZATION) $(TARGET_DEBUGGING) $(TARGET_CUSTOM_FLAGS)
else
HOSTCC = gcc
GNU_HOST_NAME = $(HOST_MACHINE)-pc-linux-gnu
TARGET_CROSS_TOP = /usr/local/$(GNU_TARGET_NAME)
TARGET_CROSS = /usr/local/bin/$(GNU_TARGET_NAME)-
TARGET_LIBDIR = $(TARGET_CROSS_TOP)/lib
TARGET_INCDIR = $(TARGET_CROSS_TOP)/include
TARGET_LDFLAGS = 
TARGET_CUSTOM_FLAGS= -pipe 
TARGET_CFLAGS=$(TARGET_OPTIMIZATION) $(TARGET_DEBUGGING) $(TARGET_CUSTOM_FLAGS)
endif
toolchain:
