TARGET_ARCH=armeb
TARGET_OS=linux
LIBC_STYLE=eglibc

LIBSTDC++_VERSION=6.0.14
LIBNSL_VERSION=2.12.2

CROSS_CONFIGURATION_GCC_VERSION=4.5.3
CROSS_CONFIGURATION_GLIBC_VERSION=2.6.1
CROSS_CONFIGURATION_GCC=gcc-$(CROSS_CONFIGURATION_GCC_VERSION)
CROSS_CONFIGURATION_GLIBC=glibc-$(CROSS_CONFIGURATION_GLIBC_VERSION)
CROSS_CONFIGURATION = $(CROSS_CONFIGURATION_GCC)-$(CROSS_CONFIGURATION_GLIBC)

#STAGING_CPPFLAGS+= -DPATH_MAX=4096 -DLINE_MAX=2048 -DMB_LEN_MAX=16

# slugos6.0-beta/tmp/sysroots/x86_64-linux/usr/armv5teb/bin/armeb-oe-linux-gnueabi-gcc

GNU_TARGET_NAME = armeb-oe-linux-gnueabi

UPD-ALT_PREFIX = /opt

ifeq ($(HOST_MACHINE),armv5teb)
HOSTCC = $(TARGET_CC)
GNU_HOST_NAME = armeb-linux
TARGET_CROSS = /usr/bin/$(GNU_TARGET_NAME)-
TARGET_LIBDIR = /usr/lib
TARGET_INCDIR = /usr/include
TARGET_LDFLAGS =
TARGET_CUSTOM_FLAGS=
TARGET_CFLAGS=$(TARGET_OPTIMIZATION) $(TARGET_DEBUGGING) $(TARGET_CUSTOM_FLAGS)
toolchain:
else
HOSTCC = gcc
GNU_HOST_NAME = $(HOST_MACHINE)-pc-linux-gnu
# TARGET_TOP = $(shell cd $(BASE_DIR)/../..; pwd)/slugos/tmp
TARGET_TOP = $(shell cd $(BASE_DIR)/../../..; pwd)/slugos/slugos6.0-beta/tmp/sysroots
TARGET_CROSS_TOP = $(TARGET_TOP)/$(HOST_MACHINE)-linux/usr/armv5teb
TARGET_CROSS = $(TARGET_CROSS_TOP)/bin/$(GNU_TARGET_NAME)-
TARGET_LIBDIR = $(TARGET_TOP)/armv5teb-oe-linux-gnueabi/usr/lib
TARGET_INCDIR = $(TARGET_TOP)/armv5teb-oe-linux-gnueabi/usr/include
TARGET_LDFLAGS = 
TARGET_CUSTOM_FLAGS= -pipe 
TARGET_CFLAGS=$(TARGET_OPTIMIZATION) $(TARGET_DEBUGGING) $(TARGET_CUSTOM_FLAGS)
LIBSTDC++_TARGET_LIBDIR = $(TARGET_LIBDIR)
toolchain:
endif
