###########################################################
#
# perl-email-mime-modifier
#
###########################################################

PERL-EMAIL-MIME-MODIFIER_SITE=http://search.cpan.org/CPAN/authors/id/R/RJ/RJBS
PERL-EMAIL-MIME-MODIFIER_VERSION=1.443
PERL-EMAIL-MIME-MODIFIER_SOURCE=Email-MIME-Modifier-$(PERL-EMAIL-MIME-MODIFIER_VERSION).tar.gz
PERL-EMAIL-MIME-MODIFIER_DIR=Email-MIME-Modifier-$(PERL-EMAIL-MIME-MODIFIER_VERSION)
PERL-EMAIL-MIME-MODIFIER_UNZIP=zcat
PERL-EMAIL-MIME-MODIFIER_MAINTAINER=NSLU2 Linux <nslu2-linux@yahoogroups.com>
PERL-EMAIL-MIME-MODIFIER_DESCRIPTION=Modify Email::MIME Objects Easily
PERL-EMAIL-MIME-MODIFIER_SECTION=email
PERL-EMAIL-MIME-MODIFIER_PRIORITY=optional
PERL-EMAIL-MIME-MODIFIER_DEPENDS=perl
PERL-EMAIL-MIME-MODIFIER_SUGGESTS=
PERL-EMAIL-MIME-MODIFIER_CONFLICTS=

PERL-EMAIL-MIME-MODIFIER_IPK_VERSION=1

PERL-EMAIL-MIME-MODIFIER_CONFFILES=

PERL-EMAIL-MIME-MODIFIER_BUILD_DIR=$(BUILD_DIR)/perl-email-mime-modifier
PERL-EMAIL-MIME-MODIFIER_SOURCE_DIR=$(SOURCE_DIR)/perl-email-mime-modifier
PERL-EMAIL-MIME-MODIFIER_IPK_DIR=$(BUILD_DIR)/perl-email-mime-modifier-$(PERL-EMAIL-MIME-MODIFIER_VERSION)-ipk
PERL-EMAIL-MIME-MODIFIER_IPK=$(BUILD_DIR)/perl-email-mime-modifier_$(PERL-EMAIL-MIME-MODIFIER_VERSION)-$(PERL-EMAIL-MIME-MODIFIER_IPK_VERSION)_$(TARGET_ARCH).ipk

$(DL_DIR)/$(PERL-EMAIL-MIME-MODIFIER_SOURCE):
	$(WGET) -P $(@D) $(PERL-EMAIL-MIME-MODIFIER_SITE)/$(@F) || \
	$(WGET) -P $(@D) $(SOURCES_NLO_SITE)/$(@F)

perl-email-mime-modifier-source: $(DL_DIR)/$(PERL-EMAIL-MIME-MODIFIER_SOURCE) $(PERL-EMAIL-MIME-MODIFIER_PATCHES)

$(PERL-EMAIL-MIME-MODIFIER_BUILD_DIR)/.configured: $(DL_DIR)/$(PERL-EMAIL-MIME-MODIFIER_SOURCE) $(PERL-EMAIL-MIME-MODIFIER_PATCHES)
	rm -rf $(BUILD_DIR)/$(PERL-EMAIL-MIME-MODIFIER_DIR) $(@D)
	$(PERL-EMAIL-MIME-MODIFIER_UNZIP) $(DL_DIR)/$(PERL-EMAIL-MIME-MODIFIER_SOURCE) | tar -C $(BUILD_DIR) -xvf -
#	cat $(PERL-EMAIL-MIME-MODIFIER_PATCHES) | patch -d $(BUILD_DIR)/$(PERL-EMAIL-MIME-MODIFIER_DIR) -p1
	mv $(BUILD_DIR)/$(PERL-EMAIL-MIME-MODIFIER_DIR) $(@D)
	(cd $(@D); \
		$(TARGET_CONFIGURE_OPTS) \
		CPPFLAGS="$(STAGING_CPPFLAGS)" \
		LDFLAGS="$(STAGING_LDFLAGS)" \
		PERL5LIB="$(STAGING_DIR)/opt/lib/perl5/site_perl" \
		$(PERL_HOSTPERL) Makefile.PL \
		PREFIX=/opt \
	)
	touch $@

perl-email-mime-modifier-unpack: $(PERL-EMAIL-MIME-MODIFIER_BUILD_DIR)/.configured

$(PERL-EMAIL-MIME-MODIFIER_BUILD_DIR)/.built: $(PERL-EMAIL-MIME-MODIFIER_BUILD_DIR)/.configured
	rm -f $@
	$(MAKE) -C $(@D) \
	PERL5LIB="$(STAGING_DIR)/opt/lib/perl5/site_perl"
	touch $@

perl-email-mime-modifier: $(PERL-EMAIL-MIME-MODIFIER_BUILD_DIR)/.built

$(PERL-EMAIL-MIME-MODIFIER_BUILD_DIR)/.staged: $(PERL-EMAIL-MIME-MODIFIER_BUILD_DIR)/.built
	rm -f $@
	$(MAKE) -C $(@D) DESTDIR=$(STAGING_DIR) install
	touch $@

perl-email-mime-modifier-stage: $(PERL-EMAIL-MIME-MODIFIER_BUILD_DIR)/.staged

$(PERL-EMAIL-MIME-MODIFIER_IPK_DIR)/CONTROL/control:
	@install -d $(@D)
	@rm -f $@
	@echo "Package: perl-email-mime-modifier" >>$@
	@echo "Architecture: $(TARGET_ARCH)" >>$@
	@echo "Priority: $(PERL-EMAIL-MIME-MODIFIER_PRIORITY)" >>$@
	@echo "Section: $(PERL-EMAIL-MIME-MODIFIER_SECTION)" >>$@
	@echo "Version: $(PERL-EMAIL-MIME-MODIFIER_VERSION)-$(PERL-EMAIL-MIME-MODIFIER_IPK_VERSION)" >>$@
	@echo "Maintainer: $(PERL-EMAIL-MIME-MODIFIER_MAINTAINER)" >>$@
	@echo "Source: $(PERL-EMAIL-MIME-MODIFIER_SITE)/$(PERL-EMAIL-MIME-MODIFIER_SOURCE)" >>$@
	@echo "Description: $(PERL-EMAIL-MIME-MODIFIER_DESCRIPTION)" >>$@
	@echo "Depends: $(PERL-EMAIL-MIME-MODIFIER_DEPENDS)" >>$@
	@echo "Suggests: $(PERL-EMAIL-MIME-MODIFIER_SUGGESTS)" >>$@
	@echo "Conflicts: $(PERL-EMAIL-MIME-MODIFIER_CONFLICTS)" >>$@

$(PERL-EMAIL-MIME-MODIFIER_IPK): $(PERL-EMAIL-MIME-MODIFIER_BUILD_DIR)/.built
	rm -rf $(PERL-EMAIL-MIME-MODIFIER_IPK_DIR) $(BUILD_DIR)/perl-email-mime-modifier_*_$(TARGET_ARCH).ipk
	$(MAKE) -C $(PERL-EMAIL-MIME-MODIFIER_BUILD_DIR) DESTDIR=$(PERL-EMAIL-MIME-MODIFIER_IPK_DIR) install
	$(MAKE) $(PERL-EMAIL-MIME-MODIFIER_IPK_DIR)/CONTROL/control
	echo $(PERL-EMAIL-MIME-MODIFIER_CONFFILES) | sed -e 's/ /\n/g' > $(PERL-EMAIL-MIME-MODIFIER_IPK_DIR)/CONTROL/conffiles
	cd $(BUILD_DIR); $(IPKG_BUILD) $(PERL-EMAIL-MIME-MODIFIER_IPK_DIR)

perl-email-mime-modifier-ipk: $(PERL-EMAIL-MIME-MODIFIER_IPK)

perl-email-mime-modifier-clean:
	-$(MAKE) -C $(PERL-EMAIL-MIME-MODIFIER_BUILD_DIR) clean

perl-email-mime-modifier-dirclean:
	rm -rf $(BUILD_DIR)/$(PERL-EMAIL-MIME-MODIFIER_DIR) $(PERL-EMAIL-MIME-MODIFIER_BUILD_DIR) $(PERL-EMAIL-MIME-MODIFIER_IPK_DIR) $(PERL-EMAIL-MIME-MODIFIER_IPK)
