--- xmail-1.22/Makefile.lnx	2005-10-12 23:35:22.000000000 +0200
+++ xmail/Makefile.lnx	2006-04-14 13:34:54.000000000 +0200
@@ -22,20 +22,20 @@
 O = o
 A = a
 CPP = cpp
-CC = g++
-LD = g++
+CC = $(CXX)
+LD = $(CXX)
 
 ifeq ($(XMAIL_DEBUG), 1)
 STRIP = touch
 CFLAGS = -g
 else
-STRIP = strip
+#STRIP = strip
 CFLAGS = -O2
 endif
 
 CFLAGS := $(CFLAGS) -I. -D__UNIX__ -D__LINUX__ -D_REENTRANT=1 -D_THREAD_SAFE=1 -DHAS_SYSMACHINE
 
-LDFLAGS = -ldl -lpthread
+LDFLAGS = -ldl -lpthread -Wl,--rpath-link=/opt/lib
 
 OUTDIR = bin
 MKMACHDEPINC = SysMachine.h
@@ -80,15 +80,15 @@
 SENDMAILOBJS = SendMail.${O}
 
 %.${O} : %.${CPP}
-	${CC} ${CPPFLAGS} ${CFLAGS} -c $*.${CPP}
+	${CXX} ${CPPFLAGS} ${CFLAGS} -c $*.${CPP}
 
 all: ${OUTDIR} ${MKMACHDEPINC} ${MAILSVR} ${CRTLCLNT} ${XMCRYPT} ${MKUSERS} ${SENDMAIL}
 
 ${OUTDIR}:
 	@mkdir ${OUTDIR}
 
-${MKMACHDEPINC}: ${MKMACHDEP}
-	./${MKMACHDEP} > ${MKMACHDEPINC}
+#${MKMACHDEPINC}: ${MKMACHDEP}
+#	./${MKMACHDEP} > ${MKMACHDEPINC}
 
 ${MKMACHDEP}: ${MKMACHDEPOBJS}
 	${LD} -o ${MKMACHDEP} ${MKMACHDEPOBJS} ${LDFLAGS}
