#!/bin/sh

echo ; echo
echo "To complete the installation, you must edit %OPTWARE_TARGET_PREFIX%/etc/motion.conf,"
echo "and then run %OPTWARE_TARGET_PREFIX%/etc/init.d/S99motion to start motion."
echo

