#!/bin/sh

/bin/mount -t ext2 /dev/mtdblock5 /mnt/config

cp /etc/init.d/optware /mnt/config/K01optware.sh
chmod ugo+x /mnt/config/K01optware.sh

echo '#!/bin/sh' > /mnt/config/K01profile.sh
echo >> /mnt/config/K01profile.sh
echo 'echo "PATH=$PATH:/opt/bin:/opt/sbin" >> /etc/profile' >> /mnt/config/K01profile.sh
chmod ugo+x /mnt/config/K01profile.sh

/bin/sync
/bin/umount /mnt/config
