#!/bin/sh

echo

# Check for the SSH1 RSA key
if [ ! -f /opt/etc/openssh/ssh_host_key ]; then
    echo Generating RSA Key...
    /opt/bin/ssh-keygen -t rsa1 -f /opt/etc/openssh/ssh_host_key -C '' -N ''
fi

# Check for the SSH2 RSA key
if [ ! -f /opt/etc/openssh/ssh_host_rsa_key ]; then
    echo Generating RSA Key...
    /opt/bin/ssh-keygen -t rsa -f /opt/etc/openssh/ssh_host_rsa_key -C '' -N ''
fi

# Check for the SSH2 DSA key
if [ ! -f /opt/etc/openssh/ssh_host_dsa_key ]; then
    echo Generating DSA Key...
    /opt/bin/ssh-keygen -t dsa -f /opt/etc/openssh/ssh_host_dsa_key -C '' -N ''
fi
                
if [ ! -d /root ];  then
    mkdir /root
fi

/opt/etc/init.d/S40sshd
