#!/bin/sh

update-alternatives --remove scp %OPTWARE_TARGET_PREFIX%/bin/openssh-scp
update-alternatives --remove ssh %OPTWARE_TARGET_PREFIX%/bin/openssh-ssh

[ -e %OPTWARE_TARGET_PREFIX%/etc/default/openssh ] && . %OPTWARE_TARGET_PREFIX%/etc/default/openssh

if [ -f %OPTWARE_TARGET_PREFIX%/var/run/sshd.pid ] ; then
  kill `cat %OPTWARE_TARGET_PREFIX%/var/run/sshd.pid`
else
  if [ -n "$SSHD_NO_PID_KILLALL" ] ; then
    killall $SSHD_NO_PID_KILLALL
  else
    killall %OPTWARE_TARGET_PREFIX%/sbin/sshd
  fi
fi

rm -f %OPTWARE_TARGET_PREFIX%/var/run/sshd.pid
