--- git-core-0.99.7-orig/Makefile	2005-09-18 15:45:59.000000000 -0700
+++ git-core/Makefile	2005-09-19 21:37:04.569540216 -0700
@@ -43,7 +43,7 @@
 GIT_VERSION = 0.99.7
 
 CFLAGS = -g -O2 -Wall
-ALL_CFLAGS = $(CFLAGS) $(PLATFORM_DEFINES) $(DEFINES)
+ALL_CFLAGS = $(CFLAGS) $(PLATFORM_DEFINES) $(DEFINES) $(CPPFLAGS)
 
 prefix = $(HOME)
 bindir = $(prefix)/bin
@@ -247,7 +247,7 @@
 	$(CC) -o $*.o -c $(ALL_CFLAGS) $<
 
 git-%: %.o $(LIB_FILE)
-	$(CC) $(ALL_CFLAGS) -o $@ $(filter %.o,$^) $(LIBS)
+	$(CC) $(ALL_CFLAGS) $(LDFLAGS) -o $@ $(filter %.o,$^) $(LIBS)
 
 git-mailinfo : SIMPLE_LIB += $(LIB_4_ICONV)
 $(SIMPLE_PROGRAMS) : $(LIB_FILE)
@@ -300,6 +300,7 @@
 install: $(PROGRAMS) $(SCRIPTS)
 	$(INSTALL) -d -m755 $(DESTDIR)$(bindir)
 	$(INSTALL) $(PROGRAMS) $(SCRIPTS) $(DESTDIR)$(bindir)
+	cd $(DESTDIR)$(bindir); $(STRIP) $(PROGRAMS)
 	$(INSTALL) git-revert $(DESTDIR)$(bindir)/git-cherry-pick
 	sh ./cmd-rename.sh $(DESTDIR)$(bindir)
 	$(MAKE) -C templates install
