#!/bin/sh

if [ ! -f /opt/etc/appWeb.conf ] ;  then
    cp /opt/doc/appweb/appWeb.conf /opt/etc/appWeb.conf
    echo ; echo
    echo "To complete the installation, you must edit /opt/etc/appWeb.conf,"
    echo "and then run /opt/etc/init.d/S81appweb to start AppWeb."
    echo
else
    /opt/etc/init.d/S81appweb
fi
