#!/bin/sh

PATH=/sbin:/bin:/usr/bin:/usr/sbin:%OPTWARE_TARGET_PREFIX%/bin:%OPTWARE_TARGET_PREFIX%/sbin

echo ; echo
echo "A template configuration file has been installed in %OPTWARE_TARGET_PREFIX%/etc/nylon.conf"
echo "Don't forget to edit it according to your needs then run %OPTWARE_TARGET_PREFIX%/etc/init.d/S10nylon"
echo

