#!/bin/sh
while true ; do
       nice %OPTWARE_TARGET_PREFIX%/bin/giftd --quiet --home-dir=/tmp/harddisk/gift \
			--local-dir=%OPTWARE_TARGET_PREFIX%/share/giFT \
			--log-file=/tmp/harddisk/gift/giftd.log
	logger "GIFT restarted due to error #$?"
	sleep 20
done

