--- cups-1.3.0/Makefile.orig	2007-07-11 14:46:42.000000000 -0700
+++ cups-1.3.0/Makefile	2007-08-17 14:18:13.000000000 -0700
@@ -229,11 +229,11 @@
 		$(RMDIR) $(BUILDROOT)$(DBUSDIR); \
 	fi
 	$(RM) $(BUILDROOT)/etc/xinetd.d/cups-lpd
-	$(RM) $(BUILDROOT)/usr/share/applications/cups.desktop
-	$(RM) $(BUILDROOT)/usr/share/icons/hicolor/16x16/apps/cups.png
-	$(RM) $(BUILDROOT)/usr/share/icons/hicolor/32x32/apps/cups.png
-	$(RM) $(BUILDROOT)/usr/share/icons/hicolor/64x64/apps/cups.png
-	$(RM) $(BUILDROOT)/usr/share/icons/hicolor/128x128/apps/cups.png
+	$(RM) $(BUILDROOT)$(prefix)/share/applications/cups.desktop
+	$(RM) $(BUILDROOT)$(prefix)/share/icons/hicolor/16x16/apps/cups.png
+	$(RM) $(BUILDROOT)$(prefix)/share/icons/hicolor/32x32/apps/cups.png
+	$(RM) $(BUILDROOT)$(prefix)/share/icons/hicolor/64x64/apps/cups.png
+	$(RM) $(BUILDROOT)$(prefix)/share/icons/hicolor/128x128/apps/cups.png
 
 
 #
