#!/bin/sh
#
# Startup script for cups lpd as standalone server
#

if [ -n "`%OPTWARE_TARGET_PREFIX%/bin/pidof cups-lpd`" ]; then
    %OPTWARE_TARGET_PREFIX%/bin/killall cups-lpd 2>/dev/null
fi

%OPTWARE_TARGET_PREFIX%/lib/cups/daemon/cups-lpd

return 0
