#!/bin/sh

echo ; echo
echo "To complete the installation, you can edit %OPTWARE_TARGET_PREFIX%/etc/chilli.conf,"
echo "and then run %OPTWARE_TARGET_PREFIX%/etc/init.d/S80chillispot to start chillispot."
echo "You can also have a look in %OPTWARE_TARGET_PREFIX%/doc/chillispot/ for some usefull third party scripts."
echo

