#!/bin/sh 
# post install script for the modutils package

set -e

# Create the /etc/modules file if it does not exist
if [ ! -e %OPTWARE_TARGET_PREFIX%/etc/modules ] ; then
	cat <<EOF > %OPTWARE_TARGET_PREFIX%/etc/modules
# %OPTWARE_TARGET_PREFIX%/etc/modules: kernel modules to load at boot time.
#
# This file should contain the names of kernel modules that are
# to be loaded at boot time, one per line.  Comments begin with
# a "#", and everything on the line after them are ignored.

EOF
	chmod 644 %OPTWARE_TARGET_PREFIX%/etc/modules
fi


if [ ! -e %OPTWARE_TARGET_PREFIX%/lib/modules/`uname -r` ] ; then
	mkdir -p %OPTWARE_TARGET_PREFIX%/lib/modules/`uname -r`
fi

exit 0
