#!/bin/sh
#
# $Id$
#

root_user=root
root_group=root
nobody_group=nobody

if grep -v root /etc/passwd > /dev/null ; then
    root_user=admin
    root_group=administrators
    sed -i -e 's/ user = root/ user = admin/' %OPTWARE_TARGET_PREFIX%/etc/dovecot/dovecot.conf
fi

if grep -v nobody /etc/passwd > /dev/null ; then
    nobody_group=guest
    sed -i -e 's/login_user = nobody/login_user = guest/' %OPTWARE_TARGET_PREFIX%/etc/dovecot/dovecot.conf
fi

mkdir -p %OPTWARE_TARGET_PREFIX%/var/run/dovecot/login
chown $root_user:$root_group %OPTWARE_TARGET_PREFIX%/var/run/dovecot
chmod 700 %OPTWARE_TARGET_PREFIX%/var/run/dovecot
chown $root_user:$nobody_group %OPTWARE_TARGET_PREFIX%/var/run/dovecot/login
chmod 750 %OPTWARE_TARGET_PREFIX%/var/run/dovecot/login
%OPTWARE_TARGET_PREFIX%/etc/init.d/S90dovecot start
