#!/bin/sh

pghome="/opt/var/pgsql"
pgdata="$pghome/data"

# create postgres user in /etc/passwd if it's not there
if grep -q ^postgres /etc/group; then
    echo There already is a postgres group on the system.
else
    echo -n "No postgres group found, creating postgres group ... "
    cat >>/etc/group <<EOF
postgres::31:
EOF
    echo ok
fi

if grep -q ^postgres /etc/passwd; then
    echo There already is a postgres user on the system.
else
    echo -n "No postgres user found, creating postgres user ... "
    cat >>/etc/passwd <<EOF
postgres:x:31:31:PostgreSQL:$pghome:/bin/sh
EOF
    echo ok
fi

# initdb if not done before
dbinited=0
if [ -d $pgdata ]; then
    echo The $pgdata directory already exists
else
    echo "No $pgdata directory found, initialize database ... "
    #mkdir -p $pgdata
    chown -R postgres:postgres $pghome
    #chmod 700 $pgdata
    su - postgres -c "/opt/bin/initdb -D $pgdata"
    echo "... database initialization done"
    dbinited=1
fi

# compatibility check and start db
/opt/etc/init.d/S98postgresql

if [ "$dbinited." = "1." -a -n "`pidof postmaster`" ]; then
    echo "Now database server is ready, you can test the connection by:"
    echo "	# su - postgres"
    echo "	$ /opt/bin/psql template1"
    echo "To allow access from other user, see http://www.postgresql.org/docs/8.0/interactive/sql-createuser.html"
    echo "To allow access from network, see http://developer.postgresql.org/docs/postgres/runtime-config.html#RUNTIME-CONFIG-CONNECTION"
fi
