#!/bin/sh


if ! grep '^/opt/lib' /etc/ld.so.conf >/dev/null 2>&1
then
	echo "Adding /opt/lib to dynamic linker configuration..."
	echo "/opt/lib" >> /etc/ld.so.conf
fi

if [ `uname -m` = armv5b ]; then
	echo "Setting up libraries"
	ln -s /lib/libgcc_s.so.1 /lib/libgcc.so.1
	ln -s /lib/libcrypto.so.0.9.7 /lib/libcrypto.so.0
	ln -s /lib/libcrypto.so.0.9.7 /lib/libcrypto.so
	ln -s /lib/libc.so.6 /lib/libc.so
	ln -s /lib/libpthread-0.9.so /lib/libpthread.so.0
	ln -s /lib/libpthread-0.9.so /lib/libpthread.so
	ln -s /lib/librt-2.2.5.so /lib/librt.so.1
	ln -s /lib/librt-2.2.5.so /lib/librt.so
	ln -s /lib/libutil-2.2.5.so /lib/libutil.so.1
	/opt/sbin/ldconfig -n /opt/lib
	echo "Setting up ipkg arch-file"
	cat >> /opt/etc/ipkg/arch.conf << EOF
arch all 1
arch any 6
arch noarch 11
arch armeb 16
arch all 21
arch armeb 26
arch nslu2 31
arch nslu2 36
EOF
fi
if [ `uname -m` = ppc ]; then
	echo "Regenerating dynamic linker cache..."
	/opt/sbin/ldconfig
fi

if ! grep '^PATH=.*/opt/bin' /etc/profile >/dev/null 2>&1
then
  echo "Modifying /etc/profile..."
  sed 's!^PATH="\(.*$\)!PATH="/opt/bin:/opt/sbin:\1!' /etc/profile > /tmp/$$ && mv /tmp/$$ /etc/profile
fi


if ! grep 'mount -o bind /volume1/opt /opt' /etc/rc.local >/dev/null 2>&1
then
  echo "Modifying /etc/rc.local"
  [ ! -e /etc/rc.local ] && echo "#!/bin/sh" >/etc/rc.local
  cat >>/etc/rc.local <<EOF

# Optware setup
[ -e /opt ] &&  [ -e /volume1/opt ] && mount -o bind /volume1/opt /opt
[ -x /opt/etc/rc.optware ] && /opt/etc/rc.optware
[ -e /bin/killall ] || ln -s /bin/busybox /bin/killall
EOF
  chmod 755 /etc/rc.local
fi

