#!/bin/sh

[ -e %OPTWARE_TARGET_PREFIX% ] || mkdir %OPTWARE_TARGET_PREFIX%
[ -e /volume1%OPTWARE_TARGET_PREFIX% ] || mkdir -p /volume1%OPTWARE_TARGET_PREFIX%
mount -o bind /volume1%OPTWARE_TARGET_PREFIX% %OPTWARE_TARGET_PREFIX%
[ -d %OPTWARE_TARGET_PREFIX%/etc/ipkg ] || mkdir -p %OPTWARE_TARGET_PREFIX%/etc/ipkg
[ -d %OPTWARE_TARGET_PREFIX%/var ] || mkdir -p %OPTWARE_TARGET_PREFIX%/var/lib
[ -d %OPTWARE_TARGET_PREFIX%/tmp ] || mkdir -p %OPTWARE_TARGET_PREFIX%/tmp
[ -d %OPTWARE_TARGET_PREFIX%/lib/ipkg/info ] || mkdir -p %OPTWARE_TARGET_PREFIX%/lib/ipkg/info
[ -d /usr/lib/ipkg/info ] || mkdir -p /usr/lib/ipkg/info
