--- Makefile	2012-06-05 13:55:53.000000000 -0400
+++ Makefile.new	2013-02-26 03:34:22.120677130 -0500
@@ -1,8 +1,8 @@
-BINS=isutf8 ifdata ifne pee sponge mispipe lckdo parallel errno
+BINS=isutf8 ifdata ifne pee sponge mispipe lckdo errno
 PERLSCRIPTS=vidir vipe ts combine zrun chronic
-MANS=sponge.1 vidir.1 vipe.1 isutf8.1 ts.1 combine.1 ifdata.1 ifne.1 pee.1 zrun.1 chronic.1 mispipe.1 lckdo.1 parallel.1 errno.1
+MANS=sponge.1 vidir.1 vipe.1 isutf8.1 ts.1 combine.1 ifdata.1 ifne.1 pee.1 zrun.1 chronic.1 mispipe.1 lckdo.1 errno.1
 CFLAGS=-O2 -g -Wall
-INSTALL_BIN?=install -s
+INSTALL_BIN?=install
 PREFIX=/usr
 
 DOCBOOK2XMAN=docbook2x-man
@@ -14,7 +14,9 @@
 
 install:
 	mkdir -p $(DESTDIR)$(PREFIX)/bin
+	$(STRIP_COMMAND) $(BINS)
 	$(INSTALL_BIN) $(BINS) $(DESTDIR)$(PREFIX)/bin
+	sed -i -e 's|/usr/bin/perl|/opt/bin/perl|g' $(PERLSCRIPTS)
 	install $(PERLSCRIPTS) $(DESTDIR)$(PREFIX)/bin
 	
 	mkdir -p $(DESTDIR)$(PREFIX)/share/man/man1
