--- cogito-0.12/Makefile.orig	2005-07-03 16:36:15.000000000 -0700
+++ cogito-0.12/Makefile	2005-07-09 20:29:48.428125000 -0700
@@ -29,6 +29,9 @@
 
 # DEFINES += -DUSE_STDEV
 
+CPPFLAGS=
+LDFLAGS=
+
 CFLAGS?=-g -O2
 CFLAGS+=-Wall $(DEFINES)
 
@@ -121,7 +124,7 @@
 endif
 endif
 
-CFLAGS += '-DSHA1_HEADER=$(SHA1_HEADER)'
+CFLAGS += $(CPPFLAGS) '-DSHA1_HEADER=$(SHA1_HEADER)'
 
 .PHONY: all git cogito
 all: git cogito
@@ -138,7 +141,7 @@
 	$(CC) $(CFLAGS) -o $@ test-date.c date.o
 
 git-%: %.o $(LIB_FILE)
-	$(CC) $(CFLAGS) -o $@ $(filter %.o,$^) $(LIBS)
+	$(CC) $(CFLAGS) -o $@ $(filter %.o,$^) $(LDFLAGS) $(LIBS)
 
 git-rev-list: LIBS += -lssl
 git-http-pull: LIBS += -lcurl
@@ -185,7 +188,7 @@
 doc:
 	$(MAKE) -C Documentation/ all
 
-sedlibdir=$(shell echo $(libdir) | sed 's/\//\\\//g')
+sedlibdir=$(shell echo "/opt/lib/cogito" | sed 's/\//\\\//g')
 
 .PHONY: install install-git install-cogito
 install: install-git install-cogito
@@ -210,6 +213,10 @@
 		cat $$file.new > $$file; rm $$file.new; \
 	done
 
+install-strip: install
+	for p in $(PROG); do $(STRIP) $(DESTDIR)$(bindir)/$$p; done
+
+
 uninstall:
 	cd $(DESTDIR)$(bindir) && rm -f $(PROG) $(SCRIPTS) $(SCRIPT) $(GEN_SCRIPT)
 	cd $(DESTDIR)$(libdir) && rm -f $(LIB_SCRIPT)
