#!/bin/sh

# TODO: check if the /opt/etc/stunnel/stunnel.conf file is unmodified, and delete it if that is the case.

echo "ipkg_remove: Warning: Not removing /opt/etc/stunnel/stunnel.conf"
echo "ipkg_remove: Warning: Not removing /opt/etc/stunnel/stunnel.pem"
