#!/bin/sh

mkdir -p %OPTWARE_TARGET_PREFIX%/etc/cron.d
mkdir -p %OPTWARE_TARGET_PREFIX%/var/cron/crontabs
mkdir -p %OPTWARE_TARGET_PREFIX%/var/run

echo "Remember that the system crontab file is \"%OPTWARE_TARGET_PREFIX%/etc/crontab\"."

%OPTWARE_TARGET_PREFIX%/etc/init.d/S10cron

