--- Makefile.moddir_rules.orig	2008-02-29 18:04:09.509651744 -0500
+++ Makefile.moddir_rules	2008-02-29 18:00:57.942774336 -0500
@@ -123,6 +123,7 @@ clean::
 
 install:: all
 	@echo "Installing modules from `basename $(CURDIR)`..."
+	$(INSTALL) -d $(DESTDIR)$(MODULES_DIR)
 	@for x in $(LOADABLE_MODS:%=%.so); do $(INSTALL) -m 755 $$x $(DESTDIR)$(MODULES_DIR) ; done
 
 uninstall::
