.TH Slimserver 1

.SH NAME slimserver \- A streaming audio server for Slimdevices Squeezeboxes, SoftSqueeze and other compatible devices.

.SH SYNOPSIS 
.B slimserver command 

.SH DESCRIPTION 
.PP \fIslimserver\fP is a shell script which starts, stops and change sone confguration parameters of the slimserver daemon. .PP This man pages was written for the optware distribution initially FSG3 because no man page is included with slimserver distribution.


.SH OPTIONS 
.PP  There are no options only commands.


.SH Commands 
.PP  There are no options only commands.

.TP 
.BI start If there was an option, it would not be -option.
.BI stop If there was an option, it would not be -option.
.BI status If there was an option, it would not be -option.
.BI enablewan start If there was an option, it would not be -option.
.BI disablewan start If there was an option, it would not be -option.



.SH RESOURCES 
.PP catapp uses almost no resources.

.SH DIAGNOSTICS The program should provide an approximate position 
where the cat ought to be found. The return value is in terms 
of time, distance and direction.


.SH COPYRIGHT 

See the file License.txt for all the copyrights relating to slimserver.

.SH BUGS 
See the slimserver bugzilla .

