#!/bin/sh

if [ ${OPTWARE_TARGET} = "nslu2" ] ; then
echo "Note that telnetd is enabled by default. Edit /opt/etc/xinetd.d/telnetd"
echo "and set 'disable=yes' to disable telnet AFTER making sure that Dropbear"
echo "or other means of logging onto your system are enabled and working."
echo
fi

echo "Warning: the current only_from configuration in /opt/etc/xinetd.conf is"
sed -n '/only_from/p' /opt/etc/xinetd.conf
echo "change to your subnet accordingly and tighten security!"

/opt/etc/init.d/S10xinetd
