#!/bin/sh

cat <<EOF

#################################################################
#
#   To automatically start smartd on bootup, edit 
#
#     %OPTWARE_TARGET_PREFIX%/etc/init.d/S20smartmontools
#
#   and follow the instructions in this file. smartd can be
#   configured in %OPTWARE_TARGET_PREFIX%/etc/smartd.conf
#
#################################################################

EOF

exit 0
