--- qemu-0.7.0/Makefile~	2005-04-27 13:52:05.000000000 -0700
+++ qemu-0.7.0/Makefile	2005-07-21 21:55:00.000000000 -0700
@@ -1,12 +1,12 @@
 -include config-host.mak
 
-CFLAGS=-Wall -O2 -g -fno-strict-aliasing 
+CFLAGS+=-fno-strict-aliasing 
 ifdef CONFIG_DARWIN
 CFLAGS+= -mdynamic-no-pic
 endif
-LDFLAGS=-g
-LIBS=
-DEFINES+=-D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE
+#LDFLAGS=-g
+#LIBS=
+DEFINES+=-D_GNU_SOURCE #-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE
 TOOLS=qemu-img$(EXESUF)
 ifdef CONFIG_STATIC
 LDFLAGS+=-static
--- qemu-0.7.0/Makefile.target~	2005-04-27 13:52:05.000000000 -0700
+++ qemu-0.7.0/Makefile.target	2005-07-21 21:55:57.000000000 -0700
@@ -14,10 +14,10 @@
 VPATH+=:$(SRC_PATH)/linux-user
 DEFINES+=-I$(SRC_PATH)/linux-user -I$(SRC_PATH)/linux-user/$(TARGET_ARCH)
 endif
-CFLAGS=-Wall -O2 -g -fno-strict-aliasing
+CFLAGS+=-fno-strict-aliasing
 #CFLAGS+=-Werror
-LDFLAGS=-g
-LIBS=
+#LDFLAGS=-g
+#LIBS=
 HELPER_CFLAGS=$(CFLAGS)
 DYNGEN=../dyngen$(EXESUF)
 # user emulator name
@@ -211,7 +211,7 @@
 
 #########################################################
 
-DEFINES+=-D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE
+DEFINES+=-D_GNU_SOURCE #-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE
 LIBS+=-lm
 ifndef CONFIG_USER_ONLY
 LIBS+=-lz
@@ -369,7 +369,7 @@
 VL_OBJS+=$(addprefix slirp/, $(SLIRP_OBJS))
 endif
 
-VL_LDFLAGS=
+VL_LDFLAGS=$(LDFLAGS)
 # specific flags are needed for non soft mmu emulator
 ifdef CONFIG_STATIC
 VL_LDFLAGS+=-static
@@ -463,7 +463,7 @@
 
 install: all 
 ifneq ($(PROGS),)
-	install -m 755 -s $(PROGS) "$(bindir)"
+	install -m 755 $(PROGS) "$(bindir)"
 endif
 
 ifneq ($(wildcard .depend),)
--- qemu/Makefile~	2005-07-24 15:43:12.000000000 -0700
+++ qemu/Makefile	2005-07-24 15:49:01.000000000 -0700
@@ -55,7 +55,7 @@
 
 install: all 
 	mkdir -p "$(bindir)"
-	install -m 755 -s $(TOOLS) "$(bindir)"
+	install -m 755 $(TOOLS) "$(bindir)"
 	mkdir -p "$(datadir)"
 	install -m 644 pc-bios/bios.bin pc-bios/vgabios.bin \
                        pc-bios/vgabios-cirrus.bin \
