#!/bin/sh

mkdir -p /opt/var/lib/rrd

if [ ! -f /opt/var/lib/rrd/memory.rrd ]; then
   rrdtool create /opt/var/lib/rrd/memory.rrd \
           DS:mem_used:GAUGE:60:U:U \
           DS:mem_free:GAUGE:60:U:U \
           DS:mem_shared:GAUGE:60:U:U \
           DS:mem_buffers:GAUGE:60:U:U \
           DS:mem_cached:GAUGE:60:U:U \
           DS:swap_used:GAUGE:60:U:U \
           RRA:AVERAGE:0.5:1:1440 \
           RRA:AVERAGE:0.01:60:744 RRA:MAX:0.01:60:744 \
           RRA:AVERAGE:0.001:720:730 RRA:MAX:0.001:720:730
fi

if [ ! -f /opt/var/lib/rrd/stat.rrd ]; then
   rrdtool create /opt/var/lib/rrd/stat.rrd \
           DS:cpu_user:GAUGE:60:U:U \
           DS:cpu_nice:GAUGE:60:U:U \
           DS:cpu_system:GAUGE:60:U:U \
           DS:cpu_idle:GAUGE:60:U:U \
           DS:ctxt:GAUGE:60:U:U \
           DS:page_in:GAUGE:60:U:U \
           DS:page_out:GAUGE:60:U:U \
           DS:processes:GAUGE:60:U:U \
           DS:swap_in:GAUGE:60:U:U \
           DS:swap_out:GAUGE:60:U:U \
           RRA:AVERAGE:0.5:1:1440 \
           RRA:AVERAGE:0.01:60:744 RRA:MAX:0.01:60:744 \
           RRA:AVERAGE:0.001:720:730 RRA:MAX:0.001:720:730
fi
