#!/bin/sh

%OPTWARE_TARGET_PREFIX%/bin/killall mountd
%OPTWARE_TARGET_PREFIX%/bin/killall statd

# TODO: check if the %OPTWARE_TARGET_PREFIX%/etc/exports file is unmodified, and delete it if that is the case.

echo "ipkg_remove: Warning: Not removing %OPTWARE_TARGET_PREFIX%/etc/exports"
