#!/bin/sh

### fix missing nsswitch.conf, so "localhost" will resolve correctly
test -e %OPTWARE_TARGET_PREFIX%/etc/nsswitch.conf || ( echo "hosts: files dns" >%OPTWARE_TARGET_PREFIX%/etc/nsswitch.conf ; chmod a+r %OPTWARE_TARGET_PREFIX%/etc/nsswitch.conf )
