#!/bin/sh

touch /opt/share/www/dokuwiki/changes.log
chown nobody /opt/share/www/dokuwiki/changes.log
chown -R nobody /opt/share/www/dokuwiki/data
chown -R nobody /opt/share/www/dokuwiki/media
chown -R nobody /opt/share/www/dokuwiki/attic
