#!/bin/sh

touch %OPTWARE_TARGET_PREFIX%/share/www/dokuwiki/changes.log
chown nobody %OPTWARE_TARGET_PREFIX%/share/www/dokuwiki/changes.log
chown -R nobody %OPTWARE_TARGET_PREFIX%/share/www/dokuwiki/data
