#!/bin/sh

mkdir -p %OPTWARE_TARGET_PREFIX%/var/mpd
chown admin %OPTWARE_TARGET_PREFIX%/var/mpd

mkdir -p %OPTWARE_TARGET_PREFIX%/var/mpd/playlists
chown admin %OPTWARE_TARGET_PREFIX%/var/mpd/playlists

echo Starting Music Playing Daemon...
%OPTWARE_TARGET_PREFIX%/etc/init.d/S61mpd
