#!/bin/sh

if [ -f %OPTWARE_TARGET_PREFIX%/var/torrentflux/db/torrentflux.db ] ; then
  echo "Old TorrentFlux database found, you will need to manually"
  echo "create a new database or upgrade the current one."
  echo "Please read %OPTWARE_TARGET_PREFIX%/doc/torrentflux/README.Optware."
else
  echo "Creating TorrentFlux database with sqlite"
  sqlite %OPTWARE_TARGET_PREFIX%/var/torrentflux/db/torrentflux.db < %OPTWARE_TARGET_PREFIX%/doc/torrentflux/sqlite_torrentflux.sql
fi
