#!/bin/sh

PATH=%OPTWARE_TARGET_PREFIX%/bin:%OPTWARE_TARGET_PREFIX%/sbin:$PATH

echo "Generating %OPTWARE_TARGET_PREFIX%/etc/machine-id"
mkdir -p %OPTWARE_TARGET_PREFIX%/etc
%OPTWARE_TARGET_PREFIX%/bin/dbus-uuidgen > %OPTWARE_TARGET_PREFIX%/etc/machine-id

# echo ; echo
# echo "A template configuration file is installed here : %OPTWARE_TARGET_PREFIX%/etc/dbus.conf"
# echo "Please read the dbus documentation to create a configuration file matching you needs."
# echo

%OPTWARE_TARGET_PREFIX%/etc/init.d/S20dbus restart
