#!/bin/sh
NEW="\\\b"
DPATH="%OPTWARE_TARGET_PREFIX%/share/nano/*.nanorc"
BPATH="%OPTWARE_TARGET_PREFIX%/share/nano/"
[ ! -d $BPATH ] && mkdir -p $BPATH || :
for f in $DPATH
do
  if [ -f $f -a -r $f ]; then
    cp $f "$f.bak"
    sed -i "s/\\\</$NEW/g" "$f"
    sed -i "s/\\\>/$NEW/g" "$f"
   else
    echo "Error: Cannot read $f"
  fi
done
