--- ../downloads/clips-6.23-Makefile	2005-02-03 17:23:03.000000000 -0800
+++ clips/clipssrc/Makefile	2005-05-28 20:37:53.174321000 -0700
@@ -15,7 +15,7 @@
  	genrcpsr.o globlbin.o globlbsc.o globlcmp.o globlcom.o \
  	globldef.o globlpsr.o immthpsr.o incrrset.o inherpsr.o \
  	inscom.o insfile.o insfun.o insmngr.o insmoddp.o insmult.o \
- 	inspsr.o insquery.o insqypsr.o iofun.o lgcldpnd.o main.o \
+ 	inspsr.o insquery.o insqypsr.o iofun.o lgcldpnd.o \
  	memalloc.o miscfun.o modulbin.o modulbsc.o modulcmp.o moduldef.o \
  	modulpsr.o modulutl.o msgcom.o msgfun.o msgpass.o msgpsr.o \
  	multifld.o multifun.o objbin.o objcmp.o objrtbin.o objrtbld.o \
@@ -28,14 +28,31 @@
  	tmpltbin.o tmpltbsc.o tmpltcmp.o tmpltdef.o tmpltfun.o tmpltlhs.o \
  	tmpltpsr.o tmpltrhs.o tmpltutl.o userdata.o utility.o watch.o
 
+SHLIB = libclips.6.23.so
+
 .c.o :
-	gcc -c -Wall  -Wundef -Wpointer-arith -Wshadow -Wcast-qual \
+	$(GCC) $(CPPFLAGS) -c -Wall  -Wundef -Wpointer-arith -Wshadow -Wcast-qual \
 	    -Wcast-align -Winline -Wmissing-declarations -Wredundant-decls \
 	    -Wmissing-prototypes -Wnested-externs \
 	    -Wstrict-prototypes -Waggregate-return -Wno-implicit $<
 
-clips : $(OBJS)
-	gcc -o clips $(OBJS) -lm -ltermcap   
+clips : $(SHLIB) main.o
+	$(GCC) -o clips main.o -L. -lclips -lm -ltermcap $(LDFLAGS)
+
+$(SHLIB): $(OBJS)
+	$(GCC) -shared -Wl,-soname,libclips.6.so -o $(SHLIB) $(OBJS)
+	ln -s $(SHLIB) libclips.6.so
+	ln -s $(SHLIB) libclips.so
+
+install:
+	install -d $(DESTDIR)/opt/bin/
+	install clips $(DESTDIR)/opt/bin
+	$(STRIP) $(DESTDIR)/opt/bin/clips
+	install -d $(DESTDIR)/opt/include/clips/
+	install *.h $(DESTDIR)/opt/include/clips/
+	install -d $(DESTDIR)/opt/lib/
+	install *.so $(DESTDIR)/opt/lib/
+	$(STRIP) $(DESTDIR)/opt/lib/$(SHLIB)
 
 agenda.o: agenda.c setup.h envrnmnt.h usrsetup.h argacces.h \
   expressn.h exprnops.h exprnpsr.h extnfunc.h symbol.h userdata.h \
