--- git-pasky-0.6.2/Makefile.orig	2005-04-22 07:08:29.000000000 +0930
+++ git-pasky-0.6.2/Makefile	2005-04-22 07:08:38.000000000 +0930
@@ -52,7 +52,7 @@
 	@echo Generating gitversion.sh...
 	@rm -f $@
 	@echo "#!/bin/sh" > $@
-	@echo "echo \"$(shell cat $(VERSION)) ($(shell commit-id))\"" >> $@
+	@echo "echo \"$(shell cat $(VERSION))\"" >> $@
 	@chmod +x $@
 
 install: $(PROG) $(GEN_SCRIPT)
