#!/bin/sh

echo

if [ ! -d /tftpboot ] ;  then
	mkdir /tftpboot
fi

if [ "`cat /etc/inetd.conf|grep 'tftp'`" = "" ]; then
    echo 'tftp  dgram   udp     wait    root    /opt/sbin/atftpd /tftpboot' >> /etc/inetd.conf
fi

/opt/etc/init.d/S60atftpd
