#!/bin/sh

prefix=%OPTWARE_TARGET_PREFIX%
pygtklibdir=${prefix}/lib/pygtk/2.0

PYTHONPATH=$pygtklibdir
export PYTHONPATH

if test -x %OPTWARE_TARGET_PREFIX%/bin/python2.7; then
exec %OPTWARE_TARGET_PREFIX%/bin/python2.7 $pygtklibdir/pygtk-demo.py
elif test -x %OPTWARE_TARGET_PREFIX%/bin/python2.6; then
exec %OPTWARE_TARGET_PREFIX%/bin/python2.6 $pygtklibdir/pygtk-demo.py
else
echo "Error: need python2.7 or python 2.6 installed to run pygtk-demo" >&2
exit 1
fi
