#!/bin/sh

echo ; echo
echo "To complete the installation, you should check %OPTWARE_TARGET_PREFIX%/etc/bpalogin.conf,"
echo "and then run %OPTWARE_TARGET_PREFIX%/etc/init.d/S05bpalogin to start bpalogin."
