#!/bin/sh

update-alternatives --install %OPTWARE_TARGET_PREFIX%/sbin/htpasswd htpasswd %OPTWARE_TARGET_PREFIX%/sbin/apache-htpasswd 60
update-alternatives --install %OPTWARE_TARGET_PREFIX%/sbin/httpd httpd %OPTWARE_TARGET_PREFIX%/sbin/apache-httpd 60

%OPTWARE_TARGET_PREFIX%/sbin/httpd -k stop
%OPTWARE_TARGET_PREFIX%/sbin/httpd -k start
