#!/bin/sh

%OPTWARE_TARGET_PREFIX%/sbin/httpd -k stop

update-alternatives --remove htpasswd %OPTWARE_TARGET_PREFIX%/sbin/apache-htpasswd
update-alternatives --remove httpd %OPTWARE_TARGET_PREFIX%/sbin/apache-httpd
