#! /bin/sh

case "$1" in
    start)
        echo "Starting Optware."
	if ! grep ' %OPTWARE_TARGET_PREFIX% ' /proc/mounts >/dev/null 2>&1 ; then
	    mkdir -p %OPTWARE_TARGET_PREFIX%
	    mount -o bind /home/.optware %OPTWARE_TARGET_PREFIX%
	fi	
	[ -x %OPTWARE_TARGET_PREFIX%/etc/rc.optware ] && %OPTWARE_TARGET_PREFIX%/etc/rc.optware
    ;;
    reconfig)
	true
    ;;
    stop)
        echo "Shutting down Optware."
	true
    ;;
    *)
        echo "Usage: $0 {start|stop|reconfig}"
        exit 1
esac

exit 0
