#!/bin/sh

[ -e /opt ] || mkdir /opt
[ -e /home/.optware ] || mkdir -p /home/.optware
if ! grep ' /opt ' /proc/mounts >/dev/null 2>&1 ; then
    mount -o bind /home/.optware /opt
fi
[ -d /opt/etc/ipkg ] || mkdir -p /opt/etc/ipkg
[ -d /opt/var ] || mkdir -p /opt/var/lib
[ -d /opt/tmp ] || mkdir -p /opt/tmp
[ -d /opt/lib/ipkg/info ] || mkdir -p /opt/lib/ipkg/info
