###########################################################
#
# perl-email-mime-contenttype
#
###########################################################

PERL-EMAIL-MIME-CONTENTTYPE_SITE=http://search.cpan.org/CPAN/authors/id/R/RJ/RJBS
PERL-EMAIL-MIME-CONTENTTYPE_VERSION=1.015
PERL-EMAIL-MIME-CONTENTTYPE_SOURCE=Email-MIME-ContentType-$(PERL-EMAIL-MIME-CONTENTTYPE_VERSION).tar.gz
PERL-EMAIL-MIME-CONTENTTYPE_DIR=Email-MIME-ContentType-$(PERL-EMAIL-MIME-CONTENTTYPE_VERSION)
PERL-EMAIL-MIME-CONTENTTYPE_UNZIP=zcat
PERL-EMAIL-MIME-CONTENTTYPE_MAINTAINER=NSLU2 Linux <nslu2-linux@yahoogroups.com>
PERL-EMAIL-MIME-CONTENTTYPE_DESCRIPTION=Parse a MIME Content-Type Header.
PERL-EMAIL-MIME-CONTENTTYPE_SECTION=email
PERL-EMAIL-MIME-CONTENTTYPE_PRIORITY=optional
PERL-EMAIL-MIME-CONTENTTYPE_DEPENDS=perl
PERL-EMAIL-MIME-CONTENTTYPE_SUGGESTS=
PERL-EMAIL-MIME-CONTENTTYPE_CONFLICTS=

PERL-EMAIL-MIME-CONTENTTYPE_IPK_VERSION=1

PERL-EMAIL-MIME-CONTENTTYPE_CONFFILES=

PERL-EMAIL-MIME-CONTENTTYPE_BUILD_DIR=$(BUILD_DIR)/perl-email-mime-contenttype
PERL-EMAIL-MIME-CONTENTTYPE_SOURCE_DIR=$(SOURCE_DIR)/perl-email-mime-contenttype
PERL-EMAIL-MIME-CONTENTTYPE_IPK_DIR=$(BUILD_DIR)/perl-email-mime-contenttype-$(PERL-EMAIL-MIME-CONTENTTYPE_VERSION)-ipk
PERL-EMAIL-MIME-CONTENTTYPE_IPK=$(BUILD_DIR)/perl-email-mime-contenttype_$(PERL-EMAIL-MIME-CONTENTTYPE_VERSION)-$(PERL-EMAIL-MIME-CONTENTTYPE_IPK_VERSION)_$(TARGET_ARCH).ipk

$(DL_DIR)/$(PERL-EMAIL-MIME-CONTENTTYPE_SOURCE):
	$(WGET) -P $(@D) $(PERL-EMAIL-MIME-CONTENTTYPE_SITE)/$(@F) || \
	$(WGET) -P $(@D) $(SOURCES_NLO_SITE)/$(@F)

perl-email-mime-contenttype-source: $(DL_DIR)/$(PERL-EMAIL-MIME-CONTENTTYPE_SOURCE) $(PERL-EMAIL-MIME-CONTENTTYPE_PATCHES)

$(PERL-EMAIL-MIME-CONTENTTYPE_BUILD_DIR)/.configured: $(DL_DIR)/$(PERL-EMAIL-MIME-CONTENTTYPE_SOURCE) $(PERL-EMAIL-MIME-CONTENTTYPE_PATCHES) make/perl-email-mime-contenttype.mk
	rm -rf $(BUILD_DIR)/$(PERL-EMAIL-MIME-CONTENTTYPE_DIR) $(@D)
	$(PERL-EMAIL-MIME-CONTENTTYPE_UNZIP) $(DL_DIR)/$(PERL-EMAIL-MIME-CONTENTTYPE_SOURCE) | tar -C $(BUILD_DIR) -xvf -
#	cat $(PERL-EMAIL-MIME-CONTENTTYPE_PATCHES) | patch -d $(BUILD_DIR)/$(PERL-EMAIL-MIME-CONTENTTYPE_DIR) -p1
	mv $(BUILD_DIR)/$(PERL-EMAIL-MIME-CONTENTTYPE_DIR) $(@D)
	(cd $(@D); \
		$(TARGET_CONFIGURE_OPTS) \
		CPPFLAGS="$(STAGING_CPPFLAGS)" \
		LDFLAGS="$(STAGING_LDFLAGS)" \
		PERL5LIB="$(STAGING_DIR)/opt/lib/perl5/site_perl" \
		$(PERL_HOSTPERL) Makefile.PL \
		PREFIX=/opt \
	)
	touch $@

perl-email-mime-contenttype-unpack: $(PERL-EMAIL-MIME-CONTENTTYPE_BUILD_DIR)/.configured

$(PERL-EMAIL-MIME-CONTENTTYPE_BUILD_DIR)/.built: $(PERL-EMAIL-MIME-CONTENTTYPE_BUILD_DIR)/.configured
	rm -f $@
	$(MAKE) -C $(@D) \
	PERL5LIB="$(STAGING_DIR)/opt/lib/perl5/site_perl"
	touch $@

perl-email-mime-contenttype: $(PERL-EMAIL-MIME-CONTENTTYPE_BUILD_DIR)/.built

$(PERL-EMAIL-MIME-CONTENTTYPE_BUILD_DIR)/.staged: $(PERL-EMAIL-MIME-CONTENTTYPE_BUILD_DIR)/.built
	rm -f $@
	$(MAKE) -C $(@D) DESTDIR=$(STAGING_DIR) install
	touch $@

perl-email-mime-contenttype-stage: $(PERL-EMAIL-MIME-CONTENTTYPE_BUILD_DIR)/.staged

$(PERL-EMAIL-MIME-CONTENTTYPE_IPK_DIR)/CONTROL/control:
	@install -d $(@D)
	@rm -f $@
	@echo "Package: perl-email-mime-contenttype" >>$@
	@echo "Architecture: $(TARGET_ARCH)" >>$@
	@echo "Priority: $(PERL-EMAIL-MIME-CONTENTTYPE_PRIORITY)" >>$@
	@echo "Section: $(PERL-EMAIL-MIME-CONTENTTYPE_SECTION)" >>$@
	@echo "Version: $(PERL-EMAIL-MIME-CONTENTTYPE_VERSION)-$(PERL-EMAIL-MIME-CONTENTTYPE_IPK_VERSION)" >>$@
	@echo "Maintainer: $(PERL-EMAIL-MIME-CONTENTTYPE_MAINTAINER)" >>$@
	@echo "Source: $(PERL-EMAIL-MIME-CONTENTTYPE_SITE)/$(PERL-EMAIL-MIME-CONTENTTYPE_SOURCE)" >>$@
	@echo "Description: $(PERL-EMAIL-MIME-CONTENTTYPE_DESCRIPTION)" >>$@
	@echo "Depends: $(PERL-EMAIL-MIME-CONTENTTYPE_DEPENDS)" >>$@
	@echo "Suggests: $(PERL-EMAIL-MIME-CONTENTTYPE_SUGGESTS)" >>$@
	@echo "Conflicts: $(PERL-EMAIL-MIME-CONTENTTYPE_CONFLICTS)" >>$@

$(PERL-EMAIL-MIME-CONTENTTYPE_IPK): $(PERL-EMAIL-MIME-CONTENTTYPE_BUILD_DIR)/.built
	rm -rf $(PERL-EMAIL-MIME-CONTENTTYPE_IPK_DIR) $(BUILD_DIR)/perl-email-mime-contenttype_*_$(TARGET_ARCH).ipk
	$(MAKE) -C $(PERL-EMAIL-MIME-CONTENTTYPE_BUILD_DIR) DESTDIR=$(PERL-EMAIL-MIME-CONTENTTYPE_IPK_DIR) install
	find $(PERL-EMAIL-MIME-CONTENTTYPE_IPK_DIR)/opt -name 'perllocal.pod' -exec rm -f {} \;
	$(MAKE) $(PERL-EMAIL-MIME-CONTENTTYPE_IPK_DIR)/CONTROL/control
	echo $(PERL-EMAIL-MIME-CONTENTTYPE_CONFFILES) | sed -e 's/ /\n/g' > $(PERL-EMAIL-MIME-CONTENTTYPE_IPK_DIR)/CONTROL/conffiles
	cd $(BUILD_DIR); $(IPKG_BUILD) $(PERL-EMAIL-MIME-CONTENTTYPE_IPK_DIR)

perl-email-mime-contenttype-ipk: $(PERL-EMAIL-MIME-CONTENTTYPE_IPK)

perl-email-mime-contenttype-clean:
	-$(MAKE) -C $(PERL-EMAIL-MIME-CONTENTTYPE_BUILD_DIR) clean

perl-email-mime-contenttype-dirclean:
	rm -rf $(BUILD_DIR)/$(PERL-EMAIL-MIME-CONTENTTYPE_DIR) $(PERL-EMAIL-MIME-CONTENTTYPE_BUILD_DIR) $(PERL-EMAIL-MIME-CONTENTTYPE_IPK_DIR) $(PERL-EMAIL-MIME-CONTENTTYPE_IPK)
