#!/bin/sh
# Description: Start / Stop MyRapBook daemon

NAME="MyRapBook"
DESC="Rapidshare Downloader Daemon"
USERNAME=name
PASSWORD=pass

case "$1" in
  start)
    cd %OPTWARE_TARGET_PREFIX%/tmp/myrapbook
    rm -rf %OPTWARE_TARGET_PREFIX%/tmp/myrapbook/cookie
    %OPTWARE_TARGET_PREFIX%/bin/curl -k --cookie-jar ./cookie --data "login=${USERNAME}&password=${PASSWORD}" https://ssl.rapidshare.com/cgi-bin/premiumzone.cgi > /dev/null
    echo "Starting $DESC: $NAME."
    %OPTWARE_TARGET_PREFIX%/bin/myrapbook-daemon
    echo " "
  ;;
  stop)
    echo -n "Stopping $DESC: $NAME"
    killall myrapbook-daemon
    echo " "
  ;;
esac
exit 0
