#!/bin/sh

echo ; echo
echo "To complete the installation, you must edit %OPTWARE_TARGET_PREFIX%/etc/ushare.conf to add the "
echo " location(s) of your media files, and then run %OPTWARE_TARGET_PREFIX%/etc/init.d/S99ushare start."
echo
