#!/bin/sh 

. %OPTWARE_TARGET_PREFIX%/etc/slimserverrm.conf
	rm -rf %OPTWARE_TARGET_PREFIX%/etc/slimserverrm.conf 2>/dev/null
	rm -rf ${SLIMSERVER_PREF} 2>/dev/null
	rm -rf ${SLIMSERVER_LOG} 2>/dev/null 
	rm -rf ${SLIMSERVER_PIDFILE} 2>/dev/null
	test `grep -c "^${SLIMSERVER_USER}" /etc/passwd` -eq 1  && deluser ${SLIMSERVER_USER} 2>/dev/null
	rm -rf %OPTWARE_TARGET_PREFIX%/share/slimserver
exit 0

