--- MoBlock-0.8/Makefile	2006-03-22 18:44:31.000000000 +0100
+++ moblock/Makefile	2007-02-23 11:45:39.000000000 +0100
@@ -7,27 +7,29 @@
 #QUEUE_LIB=LIBIPQ
 QUEUE_LIB=NFQUEUE
 
-CFLAGS=-Wall -O2 -march=i586 -mtune=i686 -fomit-frame-pointer -ffast-math \
-	-D_GNU_SOURCE -D$(QUEUE_LIB) -L/usr/include/libipq
-CC=gcc
+CC?=gcc
+STRIP?=strip
 
+CFLAGS+=-Wall -O2 -fomit-frame-pointer -ffast-math \
+	-D_GNU_SOURCE -D$(QUEUE_LIB)
+	
 all: moblock
 
 
 moblock: MoBlock.o rbt.o
-	gcc -o $@ MoBlock.o rbt.o -lnetfilter_queue -lnfnetlink
+	$(CC) -o $@ MoBlock.o rbt.o $(CFLAGS) $(LDFLAGS) -lnetfilter_queue -lnfnetlink
 	#gcc -o $@ MoBlock.o rbt.o -lipq
-	strip $@
+	$(STRIP) $@
 
 moblock-static: MoBlock.o rbt.o
-	gcc -static -o $@ MoBlock.o rbt.o -lnetfilter_queue -lnfnetlink
+	$(CC) -static -o $@ MoBlock.o rbt.o $(CFLAGS) $(LDFLAGS) -lnetfilter_queue -lnfnetlink
 	#gcc -static -o $@ MoBlock.o rbt.o -lipq
-	strip $@
+	$(STRIP) $@
 
 clean:
 	rm -f *.o *~ *# moblock
 
 install:
-	install -m 755 moblock $(DESTDIR)/usr/bin
+	install -m 755 moblock $(DESTDIR)/opt/bin
 
 .PHONY: clean
