#!/bin/sh

cat << _END_
Read the manual pages and the documentation in %OPTWARE_TARGET_PREFIX%/doc/qpopper/GUIDE.pdf

Then start the server with:
%OPTWARE_TARGET_PREFIX%/etc/init.d/S70qpopper

_END_


