#!/bin/sh

# create default cache dir
echo "create default cache and logs dir"
mkdir -p /opt/var/squid/cache
chown nobody.nobody /opt/var/squid/cache
mkdir -p /opt/var/squid/logs
chown nobody.nobody /opt/var/squid/logs

/opt/sbin/squid -z

echo
echo "You should review the configuration file /opt/etc/squid/squid.conf"
echo "make any necessary changes, and complete the install by running"
echo "/opt/etc/init.d/S80squid"
echo
