#!/bin/sh

if [ ! -f /opt/etc/raddb/radiusd.conf ] ;  then
    cp -rf /opt/doc/.radius/* /opt/etc/
    echo ; echo
    echo "To complete the installation, you must edit /opt/etc/raddb/radiusd.conf,"
    echo "and then run /opt/etc/init.d/S55freeradius to start the radius daemon."
    echo
else
    /opt/etc/init.d/S55freeradius
fi
