#!/bin/sh
#
# Startup script for ipac-ng
#
# Stop myself if running
PIDFILE=%OPTWARE_TARGET_PREFIX%/var/run/ipac.pid
[ -f ${PIDFILE} ] && kill `cat ${PIDFILE}`
echo -n "Starting ipac-ng: "
%OPTWARE_TARGET_PREFIX%/sbin/fetchipac -S
echo

