#!/bin/sh

# Installation prefix
prefix="/opt"

# Data directory
PGDATA="$prefix/var/postgresql81/data"

# Who to run the postmaster as, usually "postgres".  (NOT "root")
PGUSER=postgres

# Where to keep a log file
PGLOG="$PGDATA/serverlog"

# What to use to shut down the postmaster
PGCTL="$prefix/bin/pg_ctl"


if [ -n "`pidof postmaster`" ] ; then
	echo -n "Stopping PostgreSQL: "
	su - $PGUSER -c "$PGCTL stop -D '$PGDATA' -s -m fast"
	echo "ok"
	sleep 2
fi
