#! /bin/sh

# Add a rule to the crontab

# grep -q torrent_watchdog /etc/crontab || echo "0-59/20 * * * * root %OPTWARE_TARGET_PREFIX%/sbin/torrent_watchdog &>/dev/null" >> /etc/crontab
# m h dom mon dow user  command
grep -q torrent_watchdog %OPTWARE_TARGET_PREFIX%/etc/crontab || echo "*/30 * * * * admin nice %OPTWARE_TARGET_PREFIX%/sbin/torrent_watchdog" >> %OPTWARE_TARGET_PREFIX%/etc/crontab


# 
echo "Please note that %OPTWARE_TARGET_PREFIX%/etc/init.d/S80busybox_httpd is installed for"
echo "running CGI interface at http://localhost:8008/cgi-bin/torrent.cgi"
