#!/bin/sh


if ! grep '^%OPTWARE_TARGET_PREFIX%/lib' /etc/ld.so.conf >/dev/null 2>&1
then
	echo
	echo "Adding %OPTWARE_TARGET_PREFIX%/lib to dynamic linker configuration..."
	echo "%OPTWARE_TARGET_PREFIX%/lib" >> /etc/ld.so.conf
fi

if [ `uname -m` = armv5b ]; then
echo "Setting up ipkg arch-file"
cat >> %OPTWARE_TARGET_PREFIX%/etc/ipkg/arch.conf << EOF
arch all 1
arch any 6
arch noarch 11
arch armeb 16
arch all 21
arch armeb 26
arch nslu2 31
arch nslu2 36
EOF
fi

echo "Regenerating dynamic linker cache..."
%OPTWARE_TARGET_PREFIX%/sbin/ldconfig

if ! grep '^PATH=.*%OPTWARE_TARGET_PREFIX%/bin' /etc/profile >/dev/null 2>&1
then
  echo "Modifying /etc/profile..."
  sed 's!^PATH="\(.*$\)!PATH="%OPTWARE_TARGET_PREFIX%/bin:%OPTWARE_TARGET_PREFIX%/sbin:\1!' /etc/profile > /tmp/$$ && mv /tmp/$$ /etc/profile
fi


if ! grep 'mount -o bind /volume1%OPTWARE_TARGET_PREFIX% %OPTWARE_TARGET_PREFIX%' /etc/rc.local >/dev/null 2>&1
then
  echo "Modifying /etc/rc.local"
  [ ! -e /etc/rc.local ] && echo "#!/bin/sh" >/etc/rc.local
  cat >>/etc/rc.local <<EOF

# Optware setup
mkdir -p %OPTWARE_TARGET_PREFIX%
[ -e /volume1%OPTWARE_TARGET_PREFIX% ] && mount -o bind /volume1%OPTWARE_TARGET_PREFIX% %OPTWARE_TARGET_PREFIX%
[ -x %OPTWARE_TARGET_PREFIX%/etc/rc.optware ] && %OPTWARE_TARGET_PREFIX%/etc/rc.optware
[ -e /bin/killall ] || ln -s /bin/busybox /bin/killall
EOF
  chmod 755 /etc/rc.local
fi

