#!/bin/sh

echo "Configure gdk-pixbuf loaders"
rm -f %OPTWARE_TARGET_PREFIX%/etc/gtk-3.0/gdk-pixbuf.loaders
%OPTWARE_TARGET_PREFIX%/bin/gdk-pixbuf-query-loaders > %OPTWARE_TARGET_PREFIX%/etc/gtk-3.0/gdk-pixbuf.loaders
