#!/bin/sh

update-alternatives --install /opt/sbin/htpasswd htpasswd /opt/bin/php-thttpd-htpasswd 50

echo ; echo
echo "To complete the installation, you must edit /opt/etc/thttpd.conf,"
echo "and then run /opt/etc/init.d/S80thttpd to start thttpd."
echo

