#!/bin/sh

echo ; echo
echo "To complete the installation, you should check %OPTWARE_TARGET_PREFIX%/etc/tinyproxy/tinyproxy.conf,"
echo "and then run %OPTWARE_TARGET_PREFIX%/etc/init.d/S53tinyproxy to start tinyproxy."
echo
