#!/bin/sh 
. /opt/etc/squeezecenter.conf

cp /opt/etc/squeezecenter.conf /opt/etc/squeezecenterrm.conf

if test  -r ${SQUEEZECENTER_PIDFILE} ; then
 SQUEEZECENTER_PID=`cat ${SQUEEZECENTER_PIDFILE} 2>/dev/null`
 if test  -d /proc/${SQUEEZECENTER_PID} ; then
	kill ${SQUEEZECENTER_PID} 2>/dev/null
 fi
fi
rm -f ${SQUEEZECENTER_PIDFILE}

if test  -r ${SQUEEZECENTER_CACHEDIR}/squeezecenter-mysql.pid ; then
	kill `cat ${SQUEEZECENTER_CACHEDIR}/squeezecenter-mysql.pid` 2>/dev/null
fi

exit 0
