#!/bin/sh

adduser -S -s /dev/null -H -h /opt/share/clamav -D clamav

chown clamav:clamav /opt/share/clamav
chown clamav:clamav /opt/share/clamav/*

mkdir -p /opt/tmp
chmod 1777 /opt/tmp

mkdir -p /opt/var/log
chmod 755 /opt/var/log

touch /opt/var/log/freshclam.log
chown clamav:clamav /opt/var/log/freshclam.log 
