#!/bin/sh

mv -f /opt/lib/python2.7/site-packages/deluge/ui/web/js/extjs/ext-extensions/tree/TreeGridRenderColumn.js0000664 /opt/lib/python2.7/site-packages/deluge/ui/web/js/extjs/ext-extensions/tree/TreeGridRenderColumn.js
echo -n "Setting default deluge ui to console ... "
/opt/bin/deluge -s console
