#!/bin/sh

if [ ! -f /opt/etc/deluge/.configured ]; then
	echo -n "Setting default deluge ui to console ... "
	/opt/bin/deluge -s console
	mkdir -p /opt/etc/deluge
	touch /opt/etc/deluge/.configured
fi
