#!/bin/sh

if [ ! -f %OPTWARE_TARGET_PREFIX%/etc/deluge/.configured ]; then
	echo -n "Setting default deluge ui to console ... "
	%OPTWARE_TARGET_PREFIX%/bin/deluge -s console
	mkdir -p %OPTWARE_TARGET_PREFIX%/etc/deluge
	touch %OPTWARE_TARGET_PREFIX%/etc/deluge/.configured
fi
